// AUTO-GENERATED by scripts/local/book2-art/gen-pack-macro.js from manifest.json.
// Do NOT edit by hand. Slim apply-only manifest: just the fields the running system
// needs to re-point compendium/world documents at the durable Book II art on disk
// (no PDF geometry). Consumed by module/book2-art/reapply.js. Regenerate with:
//   node scripts/local/book2-art/gen-pack-macro.js

export const BOOK2_ART_APPLY_MANIFEST = {
 "monsters": [
  {
   "slug": "crinwin",
   "name": "Crinwin",
   "out": "assets/bestiary/crinwin.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "F0SuxRtw6dqB6Nvh",
   "journalEntryId": "Ttz6Fnr2M0HNfIre",
   "journalPageId": "FUyYoLbaxcMQ2XTA"
  },
  {
   "slug": "swyn",
   "name": "Swyn",
   "out": "assets/bestiary/swyn.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "gI80yymFTixu1alc",
   "journalEntryId": "k9Buk0QDWg2PIIqj",
   "journalPageId": "yzXUzONTGla9ZzfM"
  },
  {
   "slug": "myghal",
   "name": "Myghal, Deathless Sorcerer",
   "out": "assets/bestiary/myghal.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "xSrPam8ZFxg24LQl",
   "journalEntryId": "fhCGhdK4KZ5fBsUL",
   "journalPageId": "NadumFaGYEX4NSc0"
  },
  {
   "slug": "phantom-rider",
   "name": "Phantom Rider",
   "out": "assets/bestiary/phantom-rider.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "8T8jqS04adlc5107",
   "journalEntryId": "llEqxrhsKD2DvYdP",
   "journalPageId": "ccg4Fpzc9VeL0gBK"
  },
  {
   "slug": "servants-of-daagon",
   "name": "Servant of Daagon",
   "out": "assets/bestiary/servants-of-daagon.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "BCA8xC2gsvHO43ou",
   "journalEntryId": "SmHddXJMWp3niCln",
   "journalPageId": "EEIU9yPFNldtPXAZ"
  },
  {
   "slug": "necromancer",
   "name": "Necromancer",
   "out": "assets/bestiary/necromancer.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "58UtB8l8G68t9nRI",
   "journalEntryId": "9MF7xia8nqIu1V8N",
   "journalPageId": "DZU7wBHDfNukWLs1"
  },
  {
   "slug": "gwraig-wen",
   "name": "The Gwraig Wen",
   "out": "assets/bestiary/gwraig-wen.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "B0W8jT7lRFLJK4ds",
   "journalEntryId": "i74FkC9ROlheQBIF",
   "journalPageId": "28Ko2NCItg3Bfkf9"
  },
  {
   "slug": "willow-witches",
   "name": "Willow Witches",
   "out": "assets/bestiary/willow-witches.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "q6EfKl09RA6NKWEc",
   "journalEntryId": "M8gYXMHKcRqCshbC",
   "journalPageId": "2hPfGCxCxK6zS7th"
  },
  {
   "slug": "draventao",
   "name": "Draventao",
   "out": "assets/bestiary/draventao.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "9kcSzC3uPavigsyF",
   "journalEntryId": "sKYvwXBCiWfqNZlU",
   "journalPageId": "MxnVw08jIaPKl8MP"
  },
  {
   "slug": "llamudwr",
   "name": "Llamudwr",
   "out": "assets/bestiary/llamudwr.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "zWFuS69kPihbwlKp",
   "journalEntryId": "7qfPIuaRwuUPi4nV",
   "journalPageId": "R2kOFklneqKTwTWd"
  },
  {
   "slug": "mummified-green-lord",
   "name": "Mummified Green Lord",
   "out": "assets/bestiary/mummified-green-lord.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "TGLFOv8AqB8gHXvM",
   "journalEntryId": "EwO2lHfT38Fi7uqK",
   "journalPageId": "J8A6ThARz2TEegEV"
  },
  {
   "slug": "mummified-servant",
   "name": "Mummified Servant",
   "out": "assets/bestiary/mummified-servant.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "WVBxp5Ii2Ahd6Xln",
   "journalEntryId": "bO6QXFMmtAmKL3zO",
   "journalPageId": "ynEVoraTg5NZAlmU"
  },
  {
   "slug": "zrajedak",
   "name": "Zrajedak",
   "out": "assets/bestiary/zrajedak.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "3JaMhYyy0qDzf06q",
   "journalEntryId": "CGPfnYi6Y86dEdE0",
   "journalPageId": "vyDWFkK5vBnfGLZS"
  },
  {
   "slug": "hdour",
   "name": "Hdour",
   "out": "assets/bestiary/hdour.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "Okqc6kkhEZ3CGYKl",
   "journalEntryId": "Owbdgx7wi7p30MzW",
   "journalPageId": "yvKK2IoV4vk8Z8Dp"
  },
  {
   "slug": "hillfolk-rider",
   "name": "Hillfolk Rider",
   "out": "assets/bestiary/hillfolk-rider.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "05mh4Ag0uKxRVY8j",
   "journalEntryId": "J3KbSweAhRZfonEX",
   "journalPageId": "XwlDiMYnCmrH0CCc"
  },
  {
   "slug": "spirit-talker",
   "name": "Spirit-talker",
   "out": "assets/bestiary/spirit-talker.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "7ID9ieGRtwH4QoE8",
   "journalEntryId": "nJnOuEaIJBZParuZ",
   "journalPageId": "lqG9EkFDvTaGUVR1"
  },
  {
   "slug": "adventurer",
   "name": "Adventurer",
   "out": "assets/bestiary/adventurer.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "aAknV9EMnUjJvRL3",
   "journalEntryId": "mqbnYBt53E6uF73P",
   "journalPageId": "EAzIkasPD1rTWc2G"
  },
  {
   "slug": "antiquarian",
   "name": "Antiquarian",
   "out": "assets/bestiary/antiquarian.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "bZKtYZmapDExeAJU",
   "journalEntryId": "T1ELDbVtepRKsf3d",
   "journalPageId": "PSYUphUQPJtiNl0C"
  },
  {
   "slug": "caravan-guard",
   "name": "Caravan Guard",
   "out": "assets/bestiary/caravan-guard.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "rmNfHJdCkFfrBVIL",
   "journalEntryId": "eLDyz1PDrdPnbnG9",
   "journalPageId": "ltv7WDfMzG1MFpho"
  },
  {
   "slug": "infantry",
   "name": "Infantry",
   "out": "assets/bestiary/infantry.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "r5Ea7yfpDcp6WTO4",
   "journalEntryId": "RrC8q9cFYtODqipS",
   "journalPageId": "XN6JjsXaKtAGdhJR"
  },
  {
   "slug": "shantyara",
   "name": "Shantyara",
   "out": "assets/bestiary/shantyara.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "j8rFoANTmTHD5MKF",
   "journalEntryId": "5Sv77XzHPMBgZqJZ",
   "journalPageId": "wpyE6SCPfsbzsAj7"
  },
  {
   "slug": "fundamental",
   "name": "Fundamental",
   "out": "assets/bestiary/fundamental.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "iPBB5qDX5urJ30FU",
   "journalEntryId": "WObWuLHBHqBYlZlA",
   "journalPageId": "x2kSq3GwFhREPjAS"
  },
  {
   "slug": "the-nightingale",
   "name": "The Nightingale",
   "out": "assets/bestiary/the-nightingale.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "9h3AbAG1DBQTrtOG",
   "journalEntryId": "aGS4afk7P2DhhFN0",
   "journalPageId": "NOZWTnGdb2tXHzgM"
  },
  {
   "slug": "rime-lord",
   "name": "Rime Lord",
   "out": "assets/bestiary/rime-lord.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "knIBykmqBqa8lMFN",
   "journalEntryId": "lMOwbXpvkp9KL5SG",
   "journalPageId": "mVZaaOE7Ih4T3CNt"
  },
  {
   "slug": "horned-drake-young",
   "name": "Horned Drake (Young)",
   "out": "assets/bestiary/horned-drake-young.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "MmkSpS99xDX01jeC",
   "journalEntryId": "VJDP2ETcmA8GeHdT",
   "journalPageId": "5mYNP79ZxnvKJ8pB"
  },
  {
   "slug": "horned-drake",
   "name": "Horned Drake",
   "out": "assets/bestiary/horned-drake.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "XFmKN7n1uddyo55m",
   "journalEntryId": "VJDP2ETcmA8GeHdT",
   "journalPageId": "5mYNP79ZxnvKJ8pB"
  },
  {
   "slug": "coedwaig",
   "name": "Coedwaig",
   "out": "assets/bestiary/coedwaig.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "Hogu0AEnAffI0HHr",
   "journalEntryId": "4cuy0KcuT5WO0S5A",
   "journalPageId": "IwC0rnZcM22Hkn5D"
  },
  {
   "slug": "grwgnach",
   "name": "Grwgnach",
   "out": "assets/bestiary/grwgnach.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "QJzjWDCU8jAAb4DT",
   "journalEntryId": "YTr1h2SyKlxiRIDK",
   "journalPageId": "qXgDLWSXQxbqWkTA"
  },
  {
   "slug": "glasbren",
   "name": "Glasbren",
   "out": "assets/bestiary/glasbren.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "7GtbWc7kafUVk6dI",
   "journalEntryId": "3Q3V7QXv1XFx1UK8",
   "journalPageId": "yZnBR4myriobQFz5"
  },
  {
   "slug": "hennain",
   "name": "Hennain",
   "out": "assets/bestiary/hennain.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "6RhD3Vrdb3B9GXTA",
   "journalEntryId": "3Q3V7QXv1XFx1UK8",
   "journalPageId": "yZnBR4myriobQFz5"
  },
  {
   "slug": "lithic-servant",
   "name": "Lithic Servant",
   "out": "assets/bestiary/lithic-servant.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "CoqfzAvGUkjfvMpi",
   "journalEntryId": "91EWIGU7SaOUHbS9",
   "journalPageId": "rsVBT8SKBdg0GgA3"
  },
  {
   "slug": "mosaic-swarm",
   "name": "Mosaic Swarm",
   "out": "assets/bestiary/mosaic-swarm.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "fNEJcPa37GBqXwOq",
   "journalEntryId": "qlGSzAdbwRzcPJ70",
   "journalPageId": "rRlMBzhKYM9P4fK7"
  },
  {
   "slug": "stone-sentinel",
   "name": "Stone Sentinel",
   "out": "assets/bestiary/stone-sentinel.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "mRpMqY81O24lXlPG",
   "journalEntryId": "hNTwQMEAue41DzAx",
   "journalPageId": "5hvH8z9U9TifqPZ0"
  },
  {
   "slug": "fire-vortex",
   "name": "Fire Vortex",
   "out": "assets/bestiary/fire-vortex.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "1U5ExYjZPgmW0Gck",
   "journalEntryId": "qUp7ZkpC5FdinUC4",
   "journalPageId": "MlbyZpkmaCRWrwnL"
  },
  {
   "slug": "lightning-vortex",
   "name": "Lightning Vortex",
   "out": "assets/bestiary/lightning-vortex.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "baV7yiVwXMTKa49B",
   "journalEntryId": "qUp7ZkpC5FdinUC4",
   "journalPageId": "MlbyZpkmaCRWrwnL"
  },
  {
   "slug": "water-vortex",
   "name": "Water Vortex",
   "out": "assets/bestiary/water-vortex.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "iGFc9muBkF8HMgDQ",
   "journalEntryId": "qUp7ZkpC5FdinUC4",
   "journalPageId": "MlbyZpkmaCRWrwnL"
  },
  {
   "slug": "wind-vortex",
   "name": "Wind Vortex",
   "out": "assets/bestiary/wind-vortex.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "JRoNGWPbEVDVTu1s",
   "journalEntryId": "qUp7ZkpC5FdinUC4",
   "journalPageId": "MlbyZpkmaCRWrwnL"
  },
  {
   "slug": "the-crombil",
   "name": "The Crombil, Awakened",
   "out": "assets/bestiary/the-crombil.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "i2U1Qxscwoqw6eR0",
   "journalEntryId": "EYZ5DbxfTP8Pkzmv",
   "journalPageId": "dFx9ksncRYUgW1yL"
  },
  {
   "slug": "grimstew",
   "name": "Grimstew",
   "out": "assets/bestiary/grimstew.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "qDIbc21OgAwQJvjo",
   "journalEntryId": "fSV9XtOChfthnbDG",
   "journalPageId": "13kSx63dNzKgtIQm"
  },
  {
   "slug": "aurochs",
   "name": "Aurochs",
   "out": "assets/bestiary/aurochs.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "fVOXp33igDV70sc0",
   "journalEntryId": "tx9I3QGe5ldHuhho",
   "journalPageId": "1RDme0QvQu2hp7X9"
  },
  {
   "slug": "frythanc",
   "name": "Frythanc",
   "out": "assets/bestiary/frythanc.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "YKLG7aDPRTieTkve",
   "journalEntryId": "oAW6aV8Fmw6ZQPX4",
   "journalPageId": "LJpl17rtE9oSe9Ga"
  },
  {
   "slug": "swarm-of-silvery-vermin",
   "name": "Swarm of Silvery Vermin",
   "out": "assets/bestiary/swarm-of-silvery-vermin.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "fnzABVPboAe4m9Y8",
   "journalEntryId": "5tvhzovmN18QlxGa",
   "journalPageId": "TGra87VIxIOJstZX"
  },
  {
   "slug": "yaarowslow-the-many",
   "name": "Yaarowslow, the Many",
   "out": "assets/bestiary/yaarowslow-the-many.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "xhYYoDHoyS7ZyPKz",
   "journalEntryId": "5tvhzovmN18QlxGa",
   "journalPageId": "TGra87VIxIOJstZX"
  },
  {
   "slug": "mammoth",
   "name": "Mammoth",
   "out": "assets/bestiary/mammoth.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "cy5OhsU0kVFUoppF",
   "journalEntryId": "H4EkNtJ49Mpz9O8a",
   "journalPageId": "xX3jtpeelPVMnDBu"
  },
  {
   "slug": "tcaventes",
   "name": "Tcaventes, Shackle and Key",
   "out": "assets/bestiary/tcaventes.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "GdZQKCMmPANEuFyb",
   "journalEntryId": "muAijyov4VTFfqBL",
   "journalPageId": "FNyaslzj06Ri4wHm"
  },
  {
   "slug": "soithech",
   "name": "Soithech",
   "out": "assets/bestiary/soithech.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "R3CGOnv3X1BQUpB5",
   "journalEntryId": "J0eNyUcWDLD2ornV",
   "journalPageId": "XbjOkmGBMYByEeLN"
  },
  {
   "slug": "ghostly-hounds",
   "name": "Ghostly Hounds",
   "out": "assets/bestiary/ghostly-hounds.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "3WXpoW1ajr2PCDC9",
   "journalEntryId": "6wnyTkZl7GRhVM8g",
   "journalPageId": "6Nw4LldBvZJA3Lm8"
  },
  {
   "slug": "the-pale-hunter",
   "name": "The Pale Hunter",
   "out": "assets/bestiary/the-pale-hunter.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "KEv7LnXs4zQju3lp",
   "journalEntryId": "6wnyTkZl7GRhVM8g",
   "journalPageId": "6Nw4LldBvZJA3Lm8"
  },
  {
   "slug": "skittering-horror",
   "name": "Skittering Horror",
   "out": "assets/bestiary/skittering-horror.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "mk4kCF2buJrsSlK2",
   "journalEntryId": "KcEptvDi3nhRFoBB",
   "journalPageId": "9rYFqciEnJfFIQu8"
  },
  {
   "slug": "star-mole",
   "name": "Star-Mole",
   "out": "assets/bestiary/star-mole.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "89ZjFUUS1I9bP2MH",
   "journalEntryId": "5JC9gQCHQUHugXsQ",
   "journalPageId": "nuJLbTQh1QYWWoTg"
  },
  {
   "slug": "brawzbedr",
   "name": "Brawzbedr",
   "out": "assets/bestiary/brawzbedr.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "eU2PTY1DoA2n95RT",
   "journalEntryId": "sc28aHnwvhvBDyjh",
   "journalPageId": "pAEjZrge0FusCivY"
  },
  {
   "slug": "gouzadn",
   "name": "Gouzadn",
   "out": "assets/bestiary/gouzadn.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "SerJ5gYYlRuUmI9k",
   "journalEntryId": "IS7Y75Kbqe5KILXW",
   "journalPageId": "LO7IdRIzeEGqOvjl"
  },
  {
   "slug": "grochslon",
   "name": "Grochslon",
   "out": "assets/bestiary/grochslon.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "uP9zE6MDiS3TwIWF",
   "journalEntryId": "BUMZ5O0VT9SDjfwE",
   "journalPageId": "zvAUMz9DzP5e9Aec"
  },
  {
   "slug": "corrupted-glasbren",
   "name": "Corrupted Glasbren",
   "out": "assets/bestiary/corrupted-glasbren.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "IornEAAcH3j4YRST",
   "journalEntryId": "g8AKcpFJTeVx51xV",
   "journalPageId": "9ri6PsJH7z67a7UF"
  },
  {
   "slug": "butcherbird",
   "name": "Butcherbird",
   "out": "assets/bestiary/butcherbird.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "dLxI39zRgbt5baD5",
   "journalEntryId": "vuCG2gnrr5slc2Cj",
   "journalPageId": "PSKZl8G6n6RRlEXd"
  },
  {
   "slug": "ceirwmawr",
   "name": "Ceirwmawr",
   "out": "assets/bestiary/ceirwmawr.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "Qe9HW1xQCicVwtGC",
   "journalEntryId": "idLzu8GfQknwWCby",
   "journalPageId": "nal7Fmjmg5Grpcvw"
  },
  {
   "slug": "cynddaraig",
   "name": "Cynddaraig",
   "out": "assets/bestiary/cynddaraig.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "BVvWxKNlDdOzu9Ac",
   "journalEntryId": "JWXOAXD9nd8rkB3I",
   "journalPageId": "oXF62e14JnnztVEB"
  },
  {
   "slug": "feathered-drake",
   "name": "Feathered Drake",
   "out": "assets/bestiary/feathered-drake.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "30NDurP2YczoGj6B",
   "journalEntryId": "T17yRp50eDt8cyXO",
   "journalPageId": "57hELMNqLR2FRrIf"
  },
  {
   "slug": "hagr",
   "name": "Hagr",
   "out": "assets/bestiary/hagr.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "fz8g74CpQcYrqSki",
   "journalEntryId": "ckxdN0P9cHJfsZgQ",
   "journalPageId": "dPV0t98P6gx0ClE8"
  },
  {
   "slug": "nine-fingered-stranger",
   "name": "Nine-Fingered Stranger",
   "out": "assets/bestiary/nine-fingered-stranger.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "Kh5NQGe2zSAEV3BZ",
   "journalEntryId": "SUe3zYQvT9AGKgzG",
   "journalPageId": "m9OXzvC1peHLx1TF"
  },
  {
   "slug": "plasmic-horror",
   "name": "Plasmic Horror",
   "out": "assets/bestiary/plasmic-horror.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "nh6h60KGgx2IlxfF",
   "journalEntryId": "mBQElv2JfT8AW8KH",
   "journalPageId": "jtqfx2ZFWSNH0fpi"
  },
  {
   "slug": "kyakaara",
   "name": "Kyakaara",
   "out": "assets/bestiary/kyakaara.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "Iyc7KUONkBO5Ibyz",
   "journalEntryId": "pOtdFLTTywDCKXPM",
   "journalPageId": "aLuITGoixs7zCyQb"
  },
  {
   "slug": "kleztigr",
   "name": "Kleztigr",
   "out": "assets/bestiary/kleztigr.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "8nNyWAoSsT3VXRx5",
   "journalEntryId": "3e1HimZxPWvqLyu1",
   "journalPageId": "YjdBd1dbn0ZqMdb9"
  },
  {
   "slug": "pack-drake",
   "name": "Pack Drake",
   "out": "assets/bestiary/pack-drake.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "W7YFeowcF0yptQC3",
   "journalEntryId": "Gxjvid2IYJmTU41M",
   "journalPageId": "N96qyRiHh4FbeFhq"
  },
  {
   "slug": "crinwin-broodfather",
   "name": "Crinwin Broodfather",
   "out": "assets/bestiary/crinwin-broodfather.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "hZq0cfLjfytNVrWs",
   "journalEntryId": "Ttz6Fnr2M0HNfIre",
   "journalPageId": "FUyYoLbaxcMQ2XTA"
  },
  {
   "slug": "caralandrao",
   "name": "Caralandrao",
   "out": "assets/bestiary/caralandrao.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "PFHwDgBNwVbZHEIO",
   "journalEntryId": "eAcyCUGDDeqkLrKJ",
   "journalPageId": "cEcM0p8CnQAgBvnd"
  },
  {
   "slug": "wee-folk",
   "name": "Wee Folk",
   "out": "assets/bestiary/wee-folk.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "rL761LrHFjJcfArG",
   "journalEntryId": "aThMYefGFmE0mG73",
   "journalPageId": "wH59rdbyOwJFG5GM"
  },
  {
   "slug": "wild-horse",
   "name": "Wild Horse",
   "out": "assets/bestiary/wild-horse.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "uMjVv3GGJowiNCka",
   "journalEntryId": "nXxqWnbt932F98UJ",
   "journalPageId": "lkhQJa9UPTjB06Dn"
  },
  {
   "slug": "voidblight",
   "name": "Voidblight",
   "out": "assets/bestiary/voidblight.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "P4UPY5CmKLihfSQO",
   "journalEntryId": "smqjMCaaxstHY5nZ",
   "journalPageId": "4ajv8XIGGNNdJZVz"
  },
  {
   "slug": "shaksa",
   "name": "Shaksa",
   "out": "assets/bestiary/shaksa.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "h9IhOM9HBNmdrzUh",
   "journalEntryId": "JK9EeLUOBHfNoHCw",
   "journalPageId": "1JLAhM8J2PwfXZpJ"
  },
  {
   "slug": "hollow-fae",
   "name": "Hollow Fae",
   "out": "assets/bestiary/hollow-fae.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "0ZKo6trYa54afrSZ",
   "journalEntryId": "KgJ8NTJSYfoMhX0Y",
   "journalPageId": "LN7fbBXLMvmCRquV"
  },
  {
   "slug": "frythanc-fledgling",
   "name": "Frythanc Fledgling",
   "out": "assets/bestiary/frythanc-fledgling.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "RGU7Qtp9xioMxQ3k",
   "journalEntryId": "XiAOrP04c2oqpkDg",
   "journalPageId": "e4br5gsUdpBfugGl"
  },
  {
   "slug": "assassin",
   "name": "Assassin",
   "out": "assets/bestiary/assassin.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "x6X63ArQe1zZ3tBE",
   "journalEntryId": "ew3px3xfQiIpxEtg",
   "journalPageId": "CdxgzGw6aBI3GYEw"
  }
 ],
 "locations": [
  {
   "slug": "the-makers-roads",
   "name": "The Makers' Roads",
   "journalEntryId": "ezquwGFbne6uxzJK",
   "journalPageId": "0J5rrvhCV7xBuIej",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-makers-roads-1.webp"
    }
   ]
  },
  {
   "slug": "the-stream",
   "name": "The Stream",
   "journalEntryId": "KJUzuYlurcjPxHd7",
   "journalPageId": "qg0mwTBbWwCC2bta",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-stream-1.webp"
    }
   ]
  },
  {
   "slug": "waystones",
   "name": "Waystones",
   "journalEntryId": "VrKFDEUbYMEYplMk",
   "journalPageId": "cEPBscFh8D1YRZZn",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/waystones-1.webp"
    }
   ]
  },
  {
   "slug": "blackwater-lake",
   "name": "Blackwater Lake",
   "journalEntryId": "25HD51CKompWLFvB",
   "journalPageId": "fQLW7MZEdD2lPsML",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/blackwater-lake-1.webp"
    }
   ]
  },
  {
   "slug": "ferriers-fen",
   "name": "Ferrier's Fen",
   "journalEntryId": "UstvXnD6EA9IBBO3",
   "journalPageId": "MjRt3VmyHvOLKjkx",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/ferriers-fen-1.webp"
    }
   ]
  },
  {
   "slug": "huffel-peaks",
   "name": "Huffel Peaks",
   "journalEntryId": "RxUdCkI2lL6gE5IH",
   "journalPageId": "g4LGaNLHpQnCjw6E",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/huffel-peaks-1.webp"
    }
   ]
  },
  {
   "slug": "lygos-and-the-south",
   "name": "Lygos & the South",
   "journalEntryId": "DPUvs6Ss8UHXEsCJ",
   "journalPageId": "ZrWwwzUrqugxjDU8",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/lygos-and-the-south-1.webp"
    }
   ]
  },
  {
   "slug": "north-manmarch",
   "name": "North Manmarch",
   "journalEntryId": "NERZ6p7FNc1pxNWL",
   "journalPageId": "5FyaezhZEfD7MSAR",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/north-manmarch-1.webp"
    }
   ]
  },
  {
   "slug": "south-manmarch",
   "name": "South Manmarch",
   "journalEntryId": "apczJSWiu0M5dFrF",
   "journalPageId": "OEmiJvwbFOwASSK3",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/south-manmarch-1.webp"
    }
   ]
  },
  {
   "slug": "the-dread-river",
   "name": "The Dread River",
   "journalEntryId": "lGNIQWIn8CPHuM7E",
   "journalPageId": "rqFWDXswIplr4L8s",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-dread-river-1.webp"
    }
   ]
  },
  {
   "slug": "the-flats",
   "name": "The Flats",
   "journalEntryId": "nBvsH19B1bG2d4Di",
   "journalPageId": "hnfjCiDIWr2QPUuR",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-flats-1.webp"
    }
   ]
  },
  {
   "slug": "the-foothills",
   "name": "The Foothills",
   "journalEntryId": "61j2hjMjANZcniEQ",
   "journalPageId": "HIqfyyRDZUeRduJu",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-foothills-1.webp"
    }
   ]
  },
  {
   "slug": "the-frozen-wastes",
   "name": "The Frozen Wastes",
   "journalEntryId": "xg8MEuSbbEt1wqg8",
   "journalPageId": "UG08UT7YAyN8GoNa",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-frozen-wastes-1.webp"
    }
   ]
  },
  {
   "slug": "the-great-wood",
   "name": "The Great Wood",
   "journalEntryId": "6kt1b8ozEREDCi4k",
   "journalPageId": "OwbdRU0YCyF9qvEC",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-great-wood-1.webp"
    }
   ]
  },
  {
   "slug": "the-labyrinth",
   "name": "The Labyrinth",
   "journalEntryId": "v4slCO5mFJLcZO1q",
   "journalPageId": "0xOQrhcQ8wJFsgjT",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-labyrinth-1.webp"
    }
   ]
  },
  {
   "slug": "the-steplands",
   "name": "The Steplands",
   "journalEntryId": "No8UN1MJEb2mrLXo",
   "journalPageId": "L9aafiUeKDne11Hj",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-steplands-1.webp"
    }
   ]
  },
  {
   "slug": "the-whitefang-mountains",
   "name": "The Whitefang Mountains",
   "journalEntryId": "5vFbBIn18TKtCF91",
   "journalPageId": "9ok9WOFH6pB5E4YF",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-whitefang-mountains-1.webp"
    }
   ]
  },
  {
   "slug": "three-coven-lake",
   "name": "Three Coven Lake",
   "journalEntryId": "zUeBMA1XS4Lq3KdK",
   "journalPageId": "Ol7oAcADxdClvGZw",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/three-coven-lake-1.webp"
    }
   ]
  },
  {
   "slug": "barrier-pass",
   "name": "Barrier Pass",
   "journalEntryId": "VZ3YkXn70E1C7TEO",
   "journalPageId": "DPRYimNgfDixBLBO",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/barrier-pass-1.webp"
    }
   ]
  },
  {
   "slug": "gordins-delve",
   "name": "Gordin's Delve",
   "journalEntryId": "HesP5wBhjA0l9Ffk",
   "journalPageId": "rlqWn9hRa5shvUlY",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/gordins-delve-1.webp"
    }
   ]
  },
  {
   "slug": "marshedge",
   "name": "Marshedge",
   "journalEntryId": "uXlyry9CpXUz4ooR",
   "journalPageId": "TJgCT9BQixIEAHly",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/marshedge-1.webp"
    }
   ]
  },
  {
   "slug": "red-groves",
   "name": "Red Groves",
   "journalEntryId": "o7qpevFfrKXuVlGo",
   "journalPageId": "aAeE7ctFDrQpPARL",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/red-groves-1.webp"
    }
   ]
  },
  {
   "slug": "the-crombil",
   "name": "The Crombil",
   "journalEntryId": "UEQE5cKRurhX9gCE",
   "journalPageId": "mZBuG8teOiJRc49k",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-crombil-1.webp"
    }
   ]
  },
  {
   "slug": "the-golden-oak",
   "name": "The Golden Oak",
   "journalEntryId": "2NsZu7ZKzdrEHfjk",
   "journalPageId": "zK6zVWbEucrqHQs0",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-golden-oak-1.webp"
    }
   ]
  },
  {
   "slug": "the-maw",
   "name": "The Maw",
   "journalEntryId": "vwP9YSr3qrc4Tq7k",
   "journalPageId": "4GEczlSnuypaAiEX",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-maw-1.webp"
    }
   ]
  },
  {
   "slug": "the-ruined-tower",
   "name": "The Ruined Tower",
   "journalEntryId": "iYSktNtms4NQat8F",
   "journalPageId": "3MC797saOr3wnXwd",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-ruined-tower-1.webp"
    }
   ]
  },
  {
   "slug": "the-village-of-stonetop",
   "name": "The Village of Stonetop",
   "journalEntryId": "6yScslDfqrcCQ6CJ",
   "journalPageId": "x2BcdS6EFxG0Ic3F",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-village-of-stonetop-1.webp"
    }
   ]
  },
  {
   "slug": "titan-bones",
   "name": "Titan Bones",
   "journalEntryId": "fc9yqAlxCCgZVckC",
   "journalPageId": "oMNmCXgSQSkxerEK",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/titan-bones-1.webp"
    }
   ]
  },
  {
   "slug": "ustrina",
   "name": "Ustrina",
   "journalEntryId": "MZIqm0QhN3lxNKuO",
   "journalPageId": "B2W00k1wl8ClNwAz",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/ustrina-1.webp"
    }
   ]
  },
  {
   "slug": "vor-svetelik",
   "name": "Vor Svetelik",
   "journalEntryId": "76FKkdtTFxWEGIKQ",
   "journalPageId": "lWEakMs4PwHgcfiW",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/vor-svetelik-1.webp"
    }
   ]
  },
  {
   "slug": "the-things-below",
   "name": "The Things Below",
   "journalEntryId": "5Kym1qDHTmM8XUQ6",
   "journalPageId": "roHUFm71o2upL6Yt",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-things-below.webp"
    }
   ]
  },
  {
   "slug": "the-fae",
   "name": "The Fae",
   "journalEntryId": "Ej5WiMs30baKNXW3",
   "journalPageId": "sgMNDguHzC567bBH",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-fae-1.webp"
    }
   ]
  },
  {
   "slug": "forest-folk",
   "name": "Forest Folk",
   "journalEntryId": "wxslMExj4dQkTPfw",
   "journalPageId": "J79GdwZ5BWnwGW8q",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/forest-folk-1.webp"
    }
   ]
  },
  {
   "slug": "gods-and-religion",
   "name": "Gods & Religion",
   "journalEntryId": "s57tP3Iz6WXkfuJT",
   "journalPageId": "gkcwebWwgIxkEem3",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/gods-and-religion-1.webp"
    }
   ]
  },
  {
   "slug": "green-lords",
   "name": "Green Lords",
   "journalEntryId": "VosjScKksp5B3hsc",
   "journalPageId": "4JhUEFVSapG8Buvc",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/green-lords-1.webp"
    }
   ]
  },
  {
   "slug": "stone-lords",
   "name": "Stone Lords",
   "journalEntryId": "rJiU3RhbILojTC2u",
   "journalPageId": "7b4BpBkwhSdZ8xEN",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/stone-lords-1.webp"
    }
   ]
  },
  {
   "slug": "tempest-lords",
   "name": "Tempest Lords",
   "journalEntryId": "wsIFXTjnJFgO6vnI",
   "journalPageId": "8TvecIdm66GT2hOv",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/tempest-lords-1.webp"
    }
   ]
  },
  {
   "slug": "death-and-the-undying",
   "name": "Death & the Undying",
   "journalEntryId": "CYaQI7gy7RjF0rPH",
   "journalPageId": "EDLSG22jAIZpdwqk",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/death-and-the-undying-3.webp"
    }
   ]
  },
  {
   "slug": "forge-lords",
   "name": "Forge Lords",
   "journalEntryId": "raJkZVRsiVDqsgbj",
   "journalPageId": "08m2XNYH2Ox7Cwaw",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/forge-lords-1.webp"
    }
   ]
  },
  {
   "slug": "spirits-of-the-wild",
   "name": "Spirits of the Wild",
   "journalEntryId": "6v0jqH7HrNvALpjS",
   "journalPageId": "FD49F8IkSOQWgdQd",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/spirits-of-the-wild-1.webp"
    }
   ]
  },
  {
   "slug": "danu-the-earth-mother",
   "name": "Danu, the Earth Mother",
   "journalEntryId": "i0WjzHh0Ugynv2Tl",
   "journalPageId": "ScpAGZvgbKC5U8MR",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/danu-the-earth-mother-1.webp"
    }
   ]
  },
  {
   "slug": "artifact-creation",
   "name": "Artifact Creation",
   "journalEntryId": "mydDNbH6JBlfucco",
   "journalPageId": "D12wCjGr59wFJDZy",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/artifact-creation-1.webp"
    }
   ]
  },
  {
   "slug": "death-and-the-undying",
   "name": "Death & the Undying",
   "journalEntryId": "CYaQI7gy7RjF0rPH",
   "journalPageId": "EDLSG22jAIZpdwqk",
   "sectionIndex": 6,
   "images": [
    {
     "out": "assets/locations/death-and-the-undying-4.webp"
    }
   ]
  },
  {
   "slug": "death-and-the-undying",
   "name": "Death & the Undying",
   "journalEntryId": "CYaQI7gy7RjF0rPH",
   "journalPageId": "EDLSG22jAIZpdwqk",
   "sectionIndex": 5,
   "images": [
    {
     "out": "assets/locations/death-and-the-undying-5.webp"
    }
   ]
  },
  {
   "slug": "death-and-the-undying",
   "name": "Death & the Undying",
   "journalEntryId": "CYaQI7gy7RjF0rPH",
   "journalPageId": "EDLSG22jAIZpdwqk",
   "sectionIndex": 12,
   "images": [
    {
     "out": "assets/locations/death-and-the-undying-6.webp"
    }
   ]
  },
  {
   "slug": "forge-lords",
   "name": "Forge Lords",
   "journalEntryId": "raJkZVRsiVDqsgbj",
   "journalPageId": "08m2XNYH2Ox7Cwaw",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/forge-lords-4.webp"
    }
   ],
   "retired": [
    "assets/locations/forge-lords-6.webp"
   ]
  },
  {
   "slug": "the-golden-oak",
   "name": "The Golden Oak",
   "journalEntryId": "2NsZu7ZKzdrEHfjk",
   "journalPageId": "zK6zVWbEucrqHQs0",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/the-golden-oak-3.webp"
    }
   ]
  },
  {
   "slug": "death-and-the-undying",
   "name": "Death & the Undying",
   "journalEntryId": "CYaQI7gy7RjF0rPH",
   "journalPageId": "EDLSG22jAIZpdwqk",
   "sectionIndex": 1,
   "images": [
    {
     "out": "assets/locations/death-and-the-undying-1.webp"
    }
   ]
  },
  {
   "slug": "the-village-of-stonetop",
   "name": "The Village of Stonetop",
   "journalEntryId": "6yScslDfqrcCQ6CJ",
   "journalPageId": "x2BcdS6EFxG0Ic3F",
   "sectionIndex": 11,
   "images": [
    {
     "out": "assets/locations/the-village-of-stonetop-2.webp"
    }
   ]
  },
  {
   "slug": "the-village-of-stonetop",
   "name": "The Village of Stonetop",
   "journalEntryId": "6yScslDfqrcCQ6CJ",
   "journalPageId": "x2BcdS6EFxG0Ic3F",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/the-village-of-stonetop-3.webp"
    }
   ]
  },
  {
   "slug": "the-village-of-stonetop",
   "name": "The Village of Stonetop",
   "journalEntryId": "6yScslDfqrcCQ6CJ",
   "journalPageId": "x2BcdS6EFxG0Ic3F",
   "sectionIndex": 6,
   "images": [
    {
     "out": "assets/locations/the-village-of-stonetop-4.webp"
    }
   ]
  },
  {
   "slug": "the-village-of-stonetop",
   "name": "The Village of Stonetop",
   "journalEntryId": "6yScslDfqrcCQ6CJ",
   "journalPageId": "x2BcdS6EFxG0Ic3F",
   "sectionIndex": 7,
   "images": [
    {
     "out": "assets/locations/the-village-of-stonetop-5.webp"
    }
   ]
  },
  {
   "slug": "the-village-of-stonetop",
   "name": "The Village of Stonetop",
   "journalEntryId": "6yScslDfqrcCQ6CJ",
   "journalPageId": "x2BcdS6EFxG0Ic3F",
   "sectionIndex": 13,
   "images": [
    {
     "out": "assets/locations/the-village-of-stonetop-6.webp"
    }
   ]
  },
  {
   "slug": "barrier-pass",
   "name": "Barrier Pass",
   "journalEntryId": "VZ3YkXn70E1C7TEO",
   "journalPageId": "DPRYimNgfDixBLBO",
   "sectionIndex": 3,
   "images": [
    {
     "out": "assets/locations/barrier-pass-2.webp"
    }
   ]
  },
  {
   "slug": "barrier-pass",
   "name": "Barrier Pass",
   "journalEntryId": "VZ3YkXn70E1C7TEO",
   "journalPageId": "DPRYimNgfDixBLBO",
   "sectionIndex": 7,
   "images": [
    {
     "out": "assets/locations/barrier-pass-3.webp"
    }
   ]
  },
  {
   "slug": "blackwater-lake",
   "name": "Blackwater Lake",
   "journalEntryId": "25HD51CKompWLFvB",
   "journalPageId": "fQLW7MZEdD2lPsML",
   "sectionIndex": 3,
   "images": [
    {
     "out": "assets/locations/blackwater-lake-2.webp"
    }
   ]
  },
  {
   "slug": "blackwater-lake",
   "name": "Blackwater Lake",
   "journalEntryId": "25HD51CKompWLFvB",
   "journalPageId": "fQLW7MZEdD2lPsML",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/blackwater-lake-3.webp"
    }
   ]
  },
  {
   "slug": "blackwater-lake",
   "name": "Blackwater Lake",
   "journalEntryId": "25HD51CKompWLFvB",
   "journalPageId": "fQLW7MZEdD2lPsML",
   "sectionIndex": 5,
   "images": [
    {
     "out": "assets/locations/blackwater-lake-4.webp"
    }
   ]
  },
  {
   "slug": "death-and-the-undying",
   "name": "Death & the Undying",
   "journalEntryId": "CYaQI7gy7RjF0rPH",
   "journalPageId": "EDLSG22jAIZpdwqk",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/death-and-the-undying-2.webp"
    }
   ]
  },
  {
   "slug": "the-dread-river",
   "name": "The Dread River",
   "journalEntryId": "lGNIQWIn8CPHuM7E",
   "journalPageId": "rqFWDXswIplr4L8s",
   "sectionIndex": 3,
   "images": [
    {
     "out": "assets/locations/the-dread-river-2.webp"
    }
   ]
  },
  {
   "slug": "the-dread-river",
   "name": "The Dread River",
   "journalEntryId": "lGNIQWIn8CPHuM7E",
   "journalPageId": "rqFWDXswIplr4L8s",
   "sectionIndex": 9,
   "images": [
    {
     "out": "assets/locations/the-dread-river-3.webp"
    }
   ]
  },
  {
   "slug": "ferriers-fen",
   "name": "Ferrier's Fen",
   "journalEntryId": "UstvXnD6EA9IBBO3",
   "journalPageId": "MjRt3VmyHvOLKjkx",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/ferriers-fen-2.webp"
    }
   ]
  },
  {
   "slug": "the-flats",
   "name": "The Flats",
   "journalEntryId": "nBvsH19B1bG2d4Di",
   "journalPageId": "hnfjCiDIWr2QPUuR",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/the-flats-2.webp"
    }
   ]
  },
  {
   "slug": "the-flats",
   "name": "The Flats",
   "journalEntryId": "nBvsH19B1bG2d4Di",
   "journalPageId": "hnfjCiDIWr2QPUuR",
   "sectionIndex": 9,
   "images": [
    {
     "out": "assets/locations/the-flats-3.webp"
    }
   ]
  },
  {
   "slug": "the-flats",
   "name": "The Flats",
   "journalEntryId": "nBvsH19B1bG2d4Di",
   "journalPageId": "hnfjCiDIWr2QPUuR",
   "sectionIndex": 5,
   "images": [
    {
     "out": "assets/locations/the-flats-4.webp"
    }
   ]
  },
  {
   "slug": "the-foothills",
   "name": "The Foothills",
   "journalEntryId": "61j2hjMjANZcniEQ",
   "journalPageId": "HIqfyyRDZUeRduJu",
   "sectionIndex": 2,
   "images": [
    {
     "out": "assets/locations/the-foothills-2.webp"
    }
   ]
  },
  {
   "slug": "the-foothills",
   "name": "The Foothills",
   "journalEntryId": "61j2hjMjANZcniEQ",
   "journalPageId": "HIqfyyRDZUeRduJu",
   "sectionIndex": 6,
   "images": [
    {
     "out": "assets/locations/the-foothills-3.webp"
    }
   ]
  },
  {
   "slug": "forge-lords",
   "name": "Forge Lords",
   "journalEntryId": "raJkZVRsiVDqsgbj",
   "journalPageId": "08m2XNYH2Ox7Cwaw",
   "sectionIndex": 3,
   "images": [
    {
     "out": "assets/locations/forge-lords-3.webp"
    }
   ]
  },
  {
   "slug": "gordins-delve",
   "name": "Gordin's Delve",
   "journalEntryId": "HesP5wBhjA0l9Ffk",
   "journalPageId": "rlqWn9hRa5shvUlY",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/gordins-delve-2.webp"
    }
   ]
  },
  {
   "slug": "gordins-delve",
   "name": "Gordin's Delve",
   "journalEntryId": "HesP5wBhjA0l9Ffk",
   "journalPageId": "rlqWn9hRa5shvUlY",
   "sectionIndex": 10,
   "images": [
    {
     "out": "assets/locations/gordins-delve-3.webp"
    }
   ]
  },
  {
   "slug": "gordins-delve",
   "name": "Gordin's Delve",
   "journalEntryId": "HesP5wBhjA0l9Ffk",
   "journalPageId": "rlqWn9hRa5shvUlY",
   "sectionIndex": 11,
   "images": [
    {
     "out": "assets/locations/gordins-delve-4.webp"
    }
   ]
  },
  {
   "slug": "gordins-delve",
   "name": "Gordin's Delve",
   "journalEntryId": "HesP5wBhjA0l9Ffk",
   "journalPageId": "rlqWn9hRa5shvUlY",
   "sectionIndex": 5,
   "images": [
    {
     "out": "assets/locations/gordins-delve-5.webp"
    }
   ]
  },
  {
   "slug": "the-great-wood",
   "name": "The Great Wood",
   "journalEntryId": "6kt1b8ozEREDCi4k",
   "journalPageId": "OwbdRU0YCyF9qvEC",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/the-great-wood-2.webp"
    }
   ]
  },
  {
   "slug": "huffel-peaks",
   "name": "Huffel Peaks",
   "journalEntryId": "RxUdCkI2lL6gE5IH",
   "journalPageId": "g4LGaNLHpQnCjw6E",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/huffel-peaks-2.webp"
    }
   ]
  },
  {
   "slug": "the-labyrinth",
   "name": "The Labyrinth",
   "journalEntryId": "v4slCO5mFJLcZO1q",
   "journalPageId": "0xOQrhcQ8wJFsgjT",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/the-labyrinth-2.webp"
    }
   ]
  },
  {
   "slug": "the-labyrinth",
   "name": "The Labyrinth",
   "journalEntryId": "v4slCO5mFJLcZO1q",
   "journalPageId": "0xOQrhcQ8wJFsgjT",
   "sectionIndex": 6,
   "images": [
    {
     "out": "assets/locations/the-labyrinth-3.webp"
    }
   ]
  },
  {
   "slug": "lygos-and-the-south",
   "name": "Lygos & the South",
   "journalEntryId": "DPUvs6Ss8UHXEsCJ",
   "journalPageId": "ZrWwwzUrqugxjDU8",
   "sectionIndex": 3,
   "images": [
    {
     "out": "assets/locations/lygos-and-the-south-2.webp"
    }
   ]
  },
  {
   "slug": "lygos-and-the-south",
   "name": "Lygos & the South",
   "journalEntryId": "DPUvs6Ss8UHXEsCJ",
   "journalPageId": "ZrWwwzUrqugxjDU8",
   "sectionIndex": 5,
   "images": [
    {
     "out": "assets/locations/lygos-and-the-south-3.webp"
    }
   ]
  },
  {
   "slug": "lygos-and-the-south",
   "name": "Lygos & the South",
   "journalEntryId": "DPUvs6Ss8UHXEsCJ",
   "journalPageId": "ZrWwwzUrqugxjDU8",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/lygos-and-the-south-4.webp"
    }
   ]
  },
  {
   "slug": "lygos-and-the-south",
   "name": "Lygos & the South",
   "journalEntryId": "DPUvs6Ss8UHXEsCJ",
   "journalPageId": "ZrWwwzUrqugxjDU8",
   "sectionIndex": 2,
   "images": [
    {
     "out": "assets/locations/lygos-and-the-south-5.webp"
    }
   ]
  },
  {
   "slug": "the-makers-roads",
   "name": "The Makers' Roads",
   "journalEntryId": "ezquwGFbne6uxzJK",
   "journalPageId": "0J5rrvhCV7xBuIej",
   "sectionIndex": 7,
   "images": [
    {
     "out": "assets/locations/the-makers-roads-2.webp"
    }
   ]
  },
  {
   "slug": "marshedge",
   "name": "Marshedge",
   "journalEntryId": "uXlyry9CpXUz4ooR",
   "journalPageId": "TJgCT9BQixIEAHly",
   "sectionIndex": 9,
   "images": [
    {
     "out": "assets/locations/marshedge-2.webp"
    }
   ]
  },
  {
   "slug": "north-manmarch",
   "name": "North Manmarch",
   "journalEntryId": "NERZ6p7FNc1pxNWL",
   "journalPageId": "5FyaezhZEfD7MSAR",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/north-manmarch-2.webp"
    }
   ]
  },
  {
   "slug": "north-manmarch",
   "name": "North Manmarch",
   "journalEntryId": "NERZ6p7FNc1pxNWL",
   "journalPageId": "5FyaezhZEfD7MSAR",
   "sectionIndex": 9,
   "images": [
    {
     "out": "assets/locations/north-manmarch-3.webp"
    }
   ]
  },
  {
   "slug": "north-manmarch",
   "name": "North Manmarch",
   "journalEntryId": "NERZ6p7FNc1pxNWL",
   "journalPageId": "5FyaezhZEfD7MSAR",
   "sectionIndex": 13,
   "images": [
    {
     "out": "assets/locations/north-manmarch-4.webp"
    }
   ]
  },
  {
   "slug": "the-ruined-tower",
   "name": "The Ruined Tower",
   "journalEntryId": "iYSktNtms4NQat8F",
   "journalPageId": "3MC797saOr3wnXwd",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/the-ruined-tower-2.webp"
    }
   ]
  },
  {
   "slug": "the-ruined-tower",
   "name": "The Ruined Tower",
   "journalEntryId": "iYSktNtms4NQat8F",
   "journalPageId": "3MC797saOr3wnXwd",
   "sectionIndex": 6,
   "images": [
    {
     "out": "assets/locations/the-ruined-tower-3.webp"
    }
   ]
  },
  {
   "slug": "the-ruined-tower",
   "name": "The Ruined Tower",
   "journalEntryId": "iYSktNtms4NQat8F",
   "journalPageId": "3MC797saOr3wnXwd",
   "sectionIndex": 7,
   "images": [
    {
     "out": "assets/locations/the-ruined-tower-4.webp"
    }
   ]
  },
  {
   "slug": "the-steplands",
   "name": "The Steplands",
   "journalEntryId": "No8UN1MJEb2mrLXo",
   "journalPageId": "L9aafiUeKDne11Hj",
   "sectionIndex": 5,
   "images": [
    {
     "out": "assets/locations/the-steplands-2.webp"
    }
   ]
  },
  {
   "slug": "three-coven-lake",
   "name": "Three Coven Lake",
   "journalEntryId": "zUeBMA1XS4Lq3KdK",
   "journalPageId": "Ol7oAcADxdClvGZw",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/three-coven-lake-2.webp"
    }
   ]
  },
  {
   "slug": "vor-svetelik",
   "name": "Vor Svetelik",
   "journalEntryId": "76FKkdtTFxWEGIKQ",
   "journalPageId": "lWEakMs4PwHgcfiW",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/vor-svetelik-2.webp"
    }
   ]
  },
  {
   "slug": "vor-svetelik",
   "name": "Vor Svetelik",
   "journalEntryId": "76FKkdtTFxWEGIKQ",
   "journalPageId": "lWEakMs4PwHgcfiW",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/vor-svetelik-3.webp"
    }
   ]
  },
  {
   "slug": "vor-svetelik",
   "name": "Vor Svetelik",
   "journalEntryId": "76FKkdtTFxWEGIKQ",
   "journalPageId": "lWEakMs4PwHgcfiW",
   "sectionIndex": 6,
   "images": [
    {
     "out": "assets/locations/vor-svetelik-4.webp"
    }
   ]
  },
  {
   "slug": "the-whitefang-mountains",
   "name": "The Whitefang Mountains",
   "journalEntryId": "5vFbBIn18TKtCF91",
   "journalPageId": "9ok9WOFH6pB5E4YF",
   "sectionIndex": 14,
   "images": [
    {
     "out": "assets/locations/the-whitefang-mountains-2.webp"
    }
   ]
  },
  {
   "slug": "rime-lords",
   "name": "Rime Lords",
   "journalEntryId": "oi5Mg2wPABRjvHri",
   "journalPageId": "qq5OueNmkBJjeEKX",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/rime-lords-1.webp"
    }
   ]
  },
  {
   "slug": "forest-folk",
   "name": "Forest Folk",
   "journalEntryId": "wxslMExj4dQkTPfw",
   "journalPageId": "J79GdwZ5BWnwGW8q",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/forest-folk-2.webp"
    }
   ]
  },
  {
   "slug": "forge-lords",
   "name": "Forge Lords",
   "journalEntryId": "raJkZVRsiVDqsgbj",
   "journalPageId": "08m2XNYH2Ox7Cwaw",
   "sectionIndex": 1,
   "images": [
    {
     "out": "assets/locations/forge-lords-2.webp"
    }
   ]
  },
  {
   "slug": "forge-lords",
   "name": "Forge Lords",
   "journalEntryId": "raJkZVRsiVDqsgbj",
   "journalPageId": "08m2XNYH2Ox7Cwaw",
   "sectionIndex": 7,
   "images": [
    {
     "out": "assets/locations/forge-lords-5.webp"
    }
   ]
  },
  {
   "slug": "rime-lords",
   "name": "Rime Lords",
   "journalEntryId": "oi5Mg2wPABRjvHri",
   "journalPageId": "qq5OueNmkBJjeEKX",
   "sectionIndex": 3,
   "images": [
    {
     "out": "assets/locations/rime-lords-2.webp"
    }
   ]
  },
  {
   "slug": "rime-lords",
   "name": "Rime Lords",
   "journalEntryId": "oi5Mg2wPABRjvHri",
   "journalPageId": "qq5OueNmkBJjeEKX",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/rime-lords-3.webp"
    }
   ]
  },
  {
   "slug": "stone-lords",
   "name": "Stone Lords",
   "journalEntryId": "rJiU3RhbILojTC2u",
   "journalPageId": "7b4BpBkwhSdZ8xEN",
   "sectionIndex": 3,
   "images": [
    {
     "out": "assets/locations/stone-lords-2.webp"
    }
   ]
  },
  {
   "slug": "stone-lords",
   "name": "Stone Lords",
   "journalEntryId": "rJiU3RhbILojTC2u",
   "journalPageId": "7b4BpBkwhSdZ8xEN",
   "sectionIndex": 7,
   "images": [
    {
     "out": "assets/locations/stone-lords-4.webp"
    }
   ]
  },
  {
   "slug": "tempest-lords",
   "name": "Tempest Lords",
   "journalEntryId": "wsIFXTjnJFgO6vnI",
   "journalPageId": "8TvecIdm66GT2hOv",
   "sectionIndex": 3,
   "images": [
    {
     "out": "assets/locations/tempest-lords-2.webp"
    }
   ]
  },
  {
   "slug": "tempest-lords",
   "name": "Tempest Lords",
   "journalEntryId": "wsIFXTjnJFgO6vnI",
   "journalPageId": "8TvecIdm66GT2hOv",
   "sectionIndex": 1,
   "images": [
    {
     "out": "assets/locations/tempest-lords-3.webp"
    }
   ]
  },
  {
   "slug": "tempest-lords",
   "name": "Tempest Lords",
   "journalEntryId": "wsIFXTjnJFgO6vnI",
   "journalPageId": "8TvecIdm66GT2hOv",
   "sectionIndex": 6,
   "images": [
    {
     "out": "assets/locations/tempest-lords-4.webp"
    }
   ]
  },
  {
   "slug": "the-things-below",
   "name": "The Things Below",
   "journalEntryId": "5Kym1qDHTmM8XUQ6",
   "journalPageId": "roHUFm71o2upL6Yt",
   "sectionIndex": 12,
   "images": [
    {
     "out": "assets/locations/the-things-below-2.webp"
    }
   ]
  },
  {
   "slug": "the-things-below",
   "name": "The Things Below",
   "journalEntryId": "5Kym1qDHTmM8XUQ6",
   "journalPageId": "roHUFm71o2upL6Yt",
   "sectionIndex": 6,
   "images": [
    {
     "out": "assets/locations/the-things-below-3.webp"
    }
   ]
  },
  {
   "slug": "the-things-below",
   "name": "The Things Below",
   "journalEntryId": "5Kym1qDHTmM8XUQ6",
   "journalPageId": "roHUFm71o2upL6Yt",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/the-things-below-4.webp"
    }
   ]
  },
  {
   "slug": "the-things-below",
   "name": "The Things Below",
   "journalEntryId": "5Kym1qDHTmM8XUQ6",
   "journalPageId": "roHUFm71o2upL6Yt",
   "sectionIndex": 9,
   "images": [
    {
     "out": "assets/locations/the-things-below-5.webp"
    }
   ]
  },
  {
   "slug": "the-things-below",
   "name": "The Things Below",
   "journalEntryId": "5Kym1qDHTmM8XUQ6",
   "journalPageId": "roHUFm71o2upL6Yt",
   "sectionIndex": 15,
   "images": [
    {
     "out": "assets/locations/the-things-below-6.webp"
    }
   ]
  },
  {
   "slug": "the-things-below",
   "name": "The Things Below",
   "journalEntryId": "5Kym1qDHTmM8XUQ6",
   "journalPageId": "roHUFm71o2upL6Yt",
   "sectionIndex": 10,
   "images": [
    {
     "out": "assets/locations/the-things-below-7.webp"
    }
   ]
  }
 ],
 "settingOverviewMaps": [
  {
   "slug": "book2-vicinity",
   "name": "The Vicinity",
   "out": "assets/maps/book2-vicinity.webp",
   "journalEntryId": "stonetopSO000001",
   "journalPageId": "stonetopSOp00005",
   "replaces": [
    "assets/maps/map-vicinity.webp"
   ]
  },
  {
   "slug": "book2-worlds-end",
   "name": "The World's End",
   "out": "assets/maps/book2-worlds-end.webp",
   "journalEntryId": "stonetopSO000001",
   "journalPageId": "stonetopSOp00010",
   "replaces": [
    "assets/maps/map-worlds-end.webp"
   ]
  },
  {
   "slug": "book2-village-vista",
   "name": "The Village of Stonetop",
   "out": "assets/locations/the-village-of-stonetop-1.webp",
   "journalEntryId": "stonetopSO000001",
   "journalPageId": "stonetopSOp00004",
   "replaces": [
    "assets/maps/map-stonetop-village.webp"
   ]
  }
 ],
 "treasures": [
  {
   "slug": "the-fae-a-pot-of-gold",
   "name": "A pot of “gold”",
   "out": "assets/treasures/the-fae-a-pot-of-gold.webp"
  },
  {
   "slug": "the-fae-the-red-pennant",
   "name": "The Red Pennant",
   "out": "assets/treasures/the-fae-the-red-pennant.webp"
  },
  {
   "slug": "forge-lords-2d4-lumps-of-anthracite",
   "name": "2d4 lumps of anthracite",
   "out": "assets/treasures/forge-lords-2d4-lumps-of-anthracite.webp"
  },
  {
   "slug": "primordial-powers-a-sealed-amphora",
   "name": "A sealed amphora",
   "out": "assets/treasures/primordial-powers-a-sealed-amphora.webp"
  },
  {
   "slug": "the-things-below-a-chunk-of-red-crystal-shaped-to-look-like-a-lee",
   "name": "A chunk of red crystal, shaped to look like a leering skull",
   "out": "assets/treasures/the-things-below-a-chunk-of-red-crystal-shaped-to-look-like-a-lee.webp"
  }
 ],
 "people": [
  {
   "slug": "b1-p135-x526",
   "name": "Book I p.268",
   "out": "assets/people/b1-p135-x526.webp"
  },
  {
   "slug": "b1-p161-x611",
   "name": "Book I p.320",
   "out": "assets/people/b1-p161-x611.webp"
  },
  {
   "slug": "b1-p156-x594",
   "name": "Book I p.311",
   "out": "assets/people/b1-p156-x594.webp"
  },
  {
   "slug": "b1-p166-x630",
   "name": "Book I p.331",
   "out": "assets/people/b1-p166-x630.webp"
  },
  {
   "slug": "b1-p134-x521",
   "name": "Book I p.267",
   "out": "assets/people/b1-p134-x521.webp"
  },
  {
   "slug": "b1-p124-x490",
   "name": "Book I p.247",
   "out": "assets/people/b1-p124-x490.webp"
  },
  {
   "slug": "b1-p268-x990",
   "name": "Book I p.535",
   "out": "assets/people/b1-p268-x990.webp"
  },
  {
   "slug": "b1-p267-x987",
   "name": "Book I p.533",
   "out": "assets/people/b1-p267-x987.webp"
  },
  {
   "slug": "b1-p239-x892",
   "name": "Book I p.477",
   "out": "assets/people/b1-p239-x892.webp"
  },
  {
   "slug": "b1-p270-x998",
   "name": "Book I p.539",
   "out": "assets/people/b1-p270-x998.webp"
  },
  {
   "slug": "b2-p031-x121",
   "name": "Book II p.61",
   "out": "assets/people/b2-p031-x121.webp"
  },
  {
   "slug": "b1-p123-x486",
   "name": "Book I p.244",
   "out": "assets/people/b1-p123-x486.webp"
  },
  {
   "slug": "b1-p032-x134",
   "name": "Book I p.63",
   "out": "assets/people/b1-p032-x134.webp"
  },
  {
   "slug": "b1-p209-x792",
   "name": "Book I p.416",
   "out": "assets/people/b1-p209-x792.webp"
  },
  {
   "slug": "b1-p119-x472",
   "name": "Book I p.237",
   "out": "assets/people/b1-p119-x472.webp"
  },
  {
   "slug": "b1-p275-x1013",
   "name": "Book I p.549",
   "out": "assets/people/b1-p275-x1013.webp"
  },
  {
   "slug": "b1-p192-x723",
   "name": "Book I p.383",
   "out": "assets/people/b1-p192-x723.webp"
  },
  {
   "slug": "b1-p211-x800",
   "name": "Book I p.421",
   "out": "assets/people/b1-p211-x800.webp"
  },
  {
   "slug": "b1-p230-x864",
   "name": "Book I p.459",
   "out": "assets/people/b1-p230-x864.webp"
  },
  {
   "slug": "b1-p120-x475",
   "name": "Book I p.238",
   "out": "assets/people/b1-p120-x475.webp"
  },
  {
   "slug": "b2-p020-x76",
   "name": "Book II p.38",
   "out": "assets/people/b2-p020-x76.webp"
  },
  {
   "slug": "b1-p103-x420",
   "name": "Book I p.204",
   "out": "assets/people/b1-p103-x420.webp"
  },
  {
   "slug": "b1-p039-x161",
   "name": "Book I p.76",
   "out": "assets/people/b1-p039-x161.webp"
  },
  {
   "slug": "b1-p154-x587",
   "name": "Book I p.307",
   "out": "assets/people/b1-p154-x587.webp"
  },
  {
   "slug": "b1-p225-x847",
   "name": "Book I p.449",
   "out": "assets/people/b1-p225-x847.webp"
  },
  {
   "slug": "b1-p088-x364",
   "name": "Book I p.174",
   "out": "assets/people/b1-p088-x364.webp"
  },
  {
   "slug": "b1-p294-x1074",
   "name": "Book I p.586",
   "out": "assets/people/b1-p294-x1074.webp"
  },
  {
   "slug": "b1-p297-x1085",
   "name": "Book I p.593",
   "out": "assets/people/b1-p297-x1085.webp"
  },
  {
   "slug": "b1-p090-x372",
   "name": "Book I p.178",
   "out": "assets/people/b1-p090-x372.webp"
  },
  {
   "slug": "b1-p029-x124",
   "name": "Book I p.57",
   "out": "assets/people/b1-p029-x124.webp"
  },
  {
   "slug": "b1-p212-x803",
   "name": "Book I p.422",
   "out": "assets/people/b1-p212-x803.webp"
  },
  {
   "slug": "b1-p095-x391",
   "name": "Book I p.188",
   "out": "assets/people/b1-p095-x391.webp"
  },
  {
   "slug": "b1-p114-x454",
   "name": "Book I p.227",
   "out": "assets/people/b1-p114-x454.webp"
  },
  {
   "slug": "b1-p261-x969",
   "name": "Book I p.520",
   "out": "assets/people/b1-p261-x969.webp"
  },
  {
   "slug": "b1-p100-x411",
   "name": "Book I p.199",
   "out": "assets/people/b1-p100-x411.webp"
  },
  {
   "slug": "b1-p270-x996",
   "name": "Book I p.538",
   "out": "assets/people/b1-p270-x996.webp"
  },
  {
   "slug": "b1-p041-x169",
   "name": "Book I p.80",
   "out": "assets/people/b1-p041-x169.webp"
  },
  {
   "slug": "b1-p019-x88",
   "name": "Book I p.36",
   "out": "assets/people/b1-p019-x88.webp"
  },
  {
   "slug": "b2-p135-x539",
   "name": "Book II p.269",
   "out": "assets/people/b2-p135-x539.webp"
  },
  {
   "slug": "b1-p107-x435",
   "name": "Book I p.212",
   "out": "assets/people/b1-p107-x435.webp"
  },
  {
   "slug": "b1-p007-x32",
   "name": "Book I p.12",
   "out": "assets/people/b1-p007-x32.webp"
  },
  {
   "slug": "b1-p150-x573",
   "name": "Book I p.299",
   "out": "assets/people/b1-p150-x573.webp"
  },
  {
   "slug": "b1-p137-x533",
   "name": "Book I p.272",
   "out": "assets/people/b1-p137-x533.webp"
  },
  {
   "slug": "b1-p092-x380",
   "name": "Book I p.183",
   "out": "assets/people/b1-p092-x380.webp"
  },
  {
   "slug": "b1-p047-x193",
   "name": "Book I p.92",
   "out": "assets/people/b1-p047-x193.webp"
  },
  {
   "slug": "b1-p043-x179",
   "name": "Book I p.85",
   "out": "assets/people/b1-p043-x179.webp"
  },
  {
   "slug": "b1-p040-x165",
   "name": "Book I p.79",
   "out": "assets/people/b1-p040-x165.webp"
  },
  {
   "slug": "b1-p036-x150",
   "name": "Book I p.71",
   "out": "assets/people/b1-p036-x150.webp"
  },
  {
   "slug": "b1-p035-x145",
   "name": "Book I p.68",
   "out": "assets/people/b1-p035-x145.webp"
  },
  {
   "slug": "b1-p195-x731",
   "name": "Book I p.389",
   "out": "assets/people/b1-p195-x731.webp"
  },
  {
   "slug": "b1-p174-x658",
   "name": "Book I p.347",
   "out": "assets/people/b1-p174-x658.webp"
  },
  {
   "slug": "b1-p169-x640",
   "name": "Book I p.336",
   "out": "assets/people/b1-p169-x640.webp"
  },
  {
   "slug": "b1-p216-x816",
   "name": "Book I p.431",
   "out": "assets/people/b1-p216-x816.webp"
  },
  {
   "slug": "b1-p208-x784",
   "name": "Book I p.415",
   "out": "assets/people/b1-p208-x784.webp"
  },
  {
   "slug": "b1-p217-x820",
   "name": "Book I p.432",
   "out": "assets/people/b1-p217-x820.webp"
  },
  {
   "slug": "b1-p241-x899",
   "name": "Book I p.481",
   "out": "assets/people/b1-p241-x899.webp"
  },
  {
   "slug": "b1-p279-x1026",
   "name": "Book I p.557",
   "out": "assets/people/b1-p279-x1026.webp"
  },
  {
   "slug": "b1-p042-x173",
   "name": "Book I p.82",
   "out": "assets/people/b1-p042-x173.webp"
  },
  {
   "slug": "b1-p204-x772",
   "name": "Book I p.407",
   "out": "assets/people/b1-p204-x772.webp"
  },
  {
   "slug": "b1-p089-x368",
   "name": "Book I p.177",
   "out": "assets/people/b1-p089-x368.webp"
  },
  {
   "slug": "b1-p246-x915",
   "name": "Book I p.490",
   "out": "assets/people/b1-p246-x915.webp"
  },
  {
   "slug": "b2-p154-x619",
   "name": "Book II p.306",
   "out": "assets/people/b2-p154-x619.webp"
  },
  {
   "slug": "b2-p092-x361",
   "name": "Book II p.183",
   "out": "assets/people/b2-p092-x361.webp"
  },
  {
   "slug": "b1-p257-x953",
   "name": "Book I p.512",
   "out": "assets/people/b1-p257-x953.webp"
  },
  {
   "slug": "b1-p287-x1051",
   "name": "Book I p.573",
   "out": "assets/people/b1-p287-x1051.webp"
  },
  {
   "slug": "b1-p131-x511",
   "name": "Book I p.261",
   "out": "assets/people/b1-p131-x511.webp"
  }
 ],
 "codex": [],
 "steadings": [
  {
   "slug": "stonetop-steading",
   "name": "Stonetop",
   "out": "assets/steading/stonetop.webp"
  }
 ]
};
