// AUTO-GENERATED by scripts/local/book2-art/gen-pack-macro.js from manifest.json.
// Do NOT edit by hand. Slim apply-only manifest: just the fields the running system
// needs to re-point compendium/world documents at the durable Book II art on disk
// (no PDF geometry). Consumed by module/book2-art/reapply.js. Regenerate with:
//   node scripts/local/book2-art/gen-pack-macro.js

export const BOOK2_ART_APPLY_MANIFEST = {
 "monsters": [
  {
   "slug": "crinwin",
   "name": "Crinwin",
   "out": "assets/bestiary/crinwin.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "F0SuxRtw6dqB6Nvh",
   "journalEntryId": "Ttz6Fnr2M0HNfIre",
   "journalPageId": "FUyYoLbaxcMQ2XTA"
  },
  {
   "slug": "swyn",
   "name": "Swyn",
   "out": "assets/bestiary/swyn.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "gI80yymFTixu1alc",
   "journalEntryId": "k9Buk0QDWg2PIIqj",
   "journalPageId": "yzXUzONTGla9ZzfM"
  },
  {
   "slug": "myghal",
   "name": "Myghal, Deathless Sorcerer",
   "out": "assets/bestiary/myghal.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "xSrPam8ZFxg24LQl",
   "journalEntryId": "fhCGhdK4KZ5fBsUL",
   "journalPageId": "NadumFaGYEX4NSc0"
  },
  {
   "slug": "phantom-rider",
   "name": "Phantom Rider",
   "out": "assets/bestiary/phantom-rider.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "8T8jqS04adlc5107",
   "journalEntryId": "llEqxrhsKD2DvYdP",
   "journalPageId": "ccg4Fpzc9VeL0gBK"
  },
  {
   "slug": "servants-of-daagon",
   "name": "Servant of Daagon",
   "out": "assets/bestiary/servants-of-daagon.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "BCA8xC2gsvHO43ou",
   "journalEntryId": "SmHddXJMWp3niCln",
   "journalPageId": "EEIU9yPFNldtPXAZ"
  },
  {
   "slug": "necromancer",
   "name": "Necromancer",
   "out": "assets/bestiary/necromancer.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "58UtB8l8G68t9nRI",
   "journalEntryId": "9MF7xia8nqIu1V8N",
   "journalPageId": "DZU7wBHDfNukWLs1"
  },
  {
   "slug": "gwraig-wen",
   "name": "The Gwraig Wen",
   "out": "assets/bestiary/gwraig-wen.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "B0W8jT7lRFLJK4ds",
   "journalEntryId": "i74FkC9ROlheQBIF",
   "journalPageId": "28Ko2NCItg3Bfkf9"
  },
  {
   "slug": "willow-witches",
   "name": "Willow Witches",
   "out": "assets/bestiary/willow-witches.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "q6EfKl09RA6NKWEc",
   "journalEntryId": "M8gYXMHKcRqCshbC",
   "journalPageId": "2hPfGCxCxK6zS7th"
  },
  {
   "slug": "draventao",
   "name": "Draventao",
   "out": "assets/bestiary/draventao.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "9kcSzC3uPavigsyF",
   "journalEntryId": "sKYvwXBCiWfqNZlU",
   "journalPageId": "MxnVw08jIaPKl8MP"
  },
  {
   "slug": "llamudwr",
   "name": "Llamudwr",
   "out": "assets/bestiary/llamudwr.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "zWFuS69kPihbwlKp",
   "journalEntryId": "7qfPIuaRwuUPi4nV",
   "journalPageId": "R2kOFklneqKTwTWd"
  },
  {
   "slug": "mummified-green-lord",
   "name": "Mummified Green Lord",
   "out": "assets/bestiary/mummified-green-lord.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "TGLFOv8AqB8gHXvM",
   "journalEntryId": "EwO2lHfT38Fi7uqK",
   "journalPageId": "J8A6ThARz2TEegEV"
  },
  {
   "slug": "mummified-servant",
   "name": "Mummified Servant",
   "out": "assets/bestiary/mummified-servant.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "WVBxp5Ii2Ahd6Xln",
   "journalEntryId": "bO6QXFMmtAmKL3zO",
   "journalPageId": "ynEVoraTg5NZAlmU"
  },
  {
   "slug": "zrajedak",
   "name": "Zrajedak",
   "out": "assets/bestiary/zrajedak.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "3JaMhYyy0qDzf06q",
   "journalEntryId": "CGPfnYi6Y86dEdE0",
   "journalPageId": "vyDWFkK5vBnfGLZS"
  },
  {
   "slug": "hdour",
   "name": "Hdour",
   "out": "assets/bestiary/hdour.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "Okqc6kkhEZ3CGYKl",
   "journalEntryId": "Owbdgx7wi7p30MzW",
   "journalPageId": "yvKK2IoV4vk8Z8Dp"
  },
  {
   "slug": "hillfolk-rider",
   "name": "Hillfolk Rider",
   "out": "assets/bestiary/hillfolk-rider.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "05mh4Ag0uKxRVY8j",
   "journalEntryId": "J3KbSweAhRZfonEX",
   "journalPageId": "XwlDiMYnCmrH0CCc"
  },
  {
   "slug": "spirit-talker",
   "name": "Spirit-talker",
   "out": "assets/bestiary/spirit-talker.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "7ID9ieGRtwH4QoE8",
   "journalEntryId": "nJnOuEaIJBZParuZ",
   "journalPageId": "lqG9EkFDvTaGUVR1"
  },
  {
   "slug": "adventurer",
   "name": "Adventurer",
   "out": "assets/bestiary/adventurer.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "aAknV9EMnUjJvRL3",
   "journalEntryId": "mqbnYBt53E6uF73P",
   "journalPageId": "EAzIkasPD1rTWc2G"
  },
  {
   "slug": "antiquarian",
   "name": "Antiquarian",
   "out": "assets/bestiary/antiquarian.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "bZKtYZmapDExeAJU",
   "journalEntryId": "T1ELDbVtepRKsf3d",
   "journalPageId": "PSYUphUQPJtiNl0C"
  },
  {
   "slug": "caravan-guard",
   "name": "Caravan Guard",
   "out": "assets/bestiary/caravan-guard.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "rmNfHJdCkFfrBVIL",
   "journalEntryId": "eLDyz1PDrdPnbnG9",
   "journalPageId": "ltv7WDfMzG1MFpho"
  },
  {
   "slug": "infantry",
   "name": "Infantry",
   "out": "assets/bestiary/infantry.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "r5Ea7yfpDcp6WTO4",
   "journalEntryId": "RrC8q9cFYtODqipS",
   "journalPageId": "XN6JjsXaKtAGdhJR"
  },
  {
   "slug": "shantyara",
   "name": "Shantyara",
   "out": "assets/bestiary/shantyara.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "j8rFoANTmTHD5MKF",
   "journalEntryId": "5Sv77XzHPMBgZqJZ",
   "journalPageId": "wpyE6SCPfsbzsAj7"
  },
  {
   "slug": "fundamental",
   "name": "Fundamental",
   "out": "assets/bestiary/fundamental.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "iPBB5qDX5urJ30FU",
   "journalEntryId": "WObWuLHBHqBYlZlA",
   "journalPageId": "x2kSq3GwFhREPjAS"
  },
  {
   "slug": "the-nightingale",
   "name": "The Nightingale",
   "out": "assets/bestiary/the-nightingale.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "9h3AbAG1DBQTrtOG",
   "journalEntryId": "aGS4afk7P2DhhFN0",
   "journalPageId": "NOZWTnGdb2tXHzgM"
  },
  {
   "slug": "rime-lord",
   "name": "Rime Lord",
   "out": "assets/bestiary/rime-lord.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "knIBykmqBqa8lMFN",
   "journalEntryId": "lMOwbXpvkp9KL5SG",
   "journalPageId": "mVZaaOE7Ih4T3CNt"
  },
  {
   "slug": "horned-drake-young",
   "name": "Horned Drake (Young)",
   "out": "assets/bestiary/horned-drake-young.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "MmkSpS99xDX01jeC",
   "journalEntryId": "VJDP2ETcmA8GeHdT",
   "journalPageId": "5mYNP79ZxnvKJ8pB"
  },
  {
   "slug": "horned-drake",
   "name": "Horned Drake",
   "out": "assets/bestiary/horned-drake.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "XFmKN7n1uddyo55m",
   "journalEntryId": "VJDP2ETcmA8GeHdT",
   "journalPageId": "5mYNP79ZxnvKJ8pB"
  },
  {
   "slug": "coedwaig",
   "name": "Coedwaig",
   "out": "assets/bestiary/coedwaig.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "Hogu0AEnAffI0HHr",
   "journalEntryId": "4cuy0KcuT5WO0S5A",
   "journalPageId": "IwC0rnZcM22Hkn5D"
  },
  {
   "slug": "grwgnach",
   "name": "Grwgnach",
   "out": "assets/bestiary/grwgnach.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "QJzjWDCU8jAAb4DT",
   "journalEntryId": "YTr1h2SyKlxiRIDK",
   "journalPageId": "qXgDLWSXQxbqWkTA"
  },
  {
   "slug": "glasbren",
   "name": "Glasbren",
   "out": "assets/bestiary/glasbren.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "7GtbWc7kafUVk6dI",
   "journalEntryId": "3Q3V7QXv1XFx1UK8",
   "journalPageId": "yZnBR4myriobQFz5"
  },
  {
   "slug": "hennain",
   "name": "Hennain",
   "out": "assets/bestiary/hennain.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "6RhD3Vrdb3B9GXTA",
   "journalEntryId": "3Q3V7QXv1XFx1UK8",
   "journalPageId": "yZnBR4myriobQFz5"
  },
  {
   "slug": "lithic-servant",
   "name": "Lithic Servant",
   "out": "assets/bestiary/lithic-servant.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "CoqfzAvGUkjfvMpi",
   "journalEntryId": "91EWIGU7SaOUHbS9",
   "journalPageId": "rsVBT8SKBdg0GgA3"
  },
  {
   "slug": "mosaic-swarm",
   "name": "Mosaic Swarm",
   "out": "assets/bestiary/mosaic-swarm.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "fNEJcPa37GBqXwOq",
   "journalEntryId": "qlGSzAdbwRzcPJ70",
   "journalPageId": "rRlMBzhKYM9P4fK7"
  },
  {
   "slug": "stone-sentinel",
   "name": "Stone Sentinel",
   "out": "assets/bestiary/stone-sentinel.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "mRpMqY81O24lXlPG",
   "journalEntryId": "hNTwQMEAue41DzAx",
   "journalPageId": "5hvH8z9U9TifqPZ0"
  },
  {
   "slug": "fire-vortex",
   "name": "Fire Vortex",
   "out": "assets/bestiary/fire-vortex.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "1U5ExYjZPgmW0Gck",
   "journalEntryId": "qUp7ZkpC5FdinUC4",
   "journalPageId": "MlbyZpkmaCRWrwnL"
  },
  {
   "slug": "lightning-vortex",
   "name": "Lightning Vortex",
   "out": "assets/bestiary/lightning-vortex.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "baV7yiVwXMTKa49B",
   "journalEntryId": "qUp7ZkpC5FdinUC4",
   "journalPageId": "MlbyZpkmaCRWrwnL"
  },
  {
   "slug": "water-vortex",
   "name": "Water Vortex",
   "out": "assets/bestiary/water-vortex.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "iGFc9muBkF8HMgDQ",
   "journalEntryId": "qUp7ZkpC5FdinUC4",
   "journalPageId": "MlbyZpkmaCRWrwnL"
  },
  {
   "slug": "wind-vortex",
   "name": "Wind Vortex",
   "out": "assets/bestiary/wind-vortex.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "JRoNGWPbEVDVTu1s",
   "journalEntryId": "qUp7ZkpC5FdinUC4",
   "journalPageId": "MlbyZpkmaCRWrwnL"
  },
  {
   "slug": "the-crombil",
   "name": "The Crombil, Awakened",
   "out": "assets/bestiary/the-crombil.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "i2U1Qxscwoqw6eR0",
   "journalEntryId": "EYZ5DbxfTP8Pkzmv",
   "journalPageId": "dFx9ksncRYUgW1yL"
  },
  {
   "slug": "grimstew",
   "name": "Grimstew",
   "out": "assets/bestiary/grimstew.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "qDIbc21OgAwQJvjo",
   "journalEntryId": "fSV9XtOChfthnbDG",
   "journalPageId": "13kSx63dNzKgtIQm"
  },
  {
   "slug": "aurochs",
   "name": "Aurochs",
   "out": "assets/bestiary/aurochs.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "fVOXp33igDV70sc0",
   "journalEntryId": "tx9I3QGe5ldHuhho",
   "journalPageId": "1RDme0QvQu2hp7X9"
  },
  {
   "slug": "frythanc",
   "name": "Frythanc",
   "out": "assets/bestiary/frythanc.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "YKLG7aDPRTieTkve",
   "journalEntryId": "oAW6aV8Fmw6ZQPX4",
   "journalPageId": "LJpl17rtE9oSe9Ga"
  },
  {
   "slug": "swarm-of-silvery-vermin",
   "name": "Swarm of Silvery Vermin",
   "out": "assets/bestiary/swarm-of-silvery-vermin.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "fnzABVPboAe4m9Y8",
   "journalEntryId": "5tvhzovmN18QlxGa",
   "journalPageId": "TGra87VIxIOJstZX"
  },
  {
   "slug": "yaarowslow-the-many",
   "name": "Yaarowslow, the Many",
   "out": "assets/bestiary/yaarowslow-the-many.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "xhYYoDHoyS7ZyPKz",
   "journalEntryId": "5tvhzovmN18QlxGa",
   "journalPageId": "TGra87VIxIOJstZX"
  },
  {
   "slug": "mammoth",
   "name": "Mammoth",
   "out": "assets/bestiary/mammoth.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "cy5OhsU0kVFUoppF",
   "journalEntryId": "H4EkNtJ49Mpz9O8a",
   "journalPageId": "xX3jtpeelPVMnDBu"
  },
  {
   "slug": "tcaventes",
   "name": "Tcaventes, Shackle and Key",
   "out": "assets/bestiary/tcaventes.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "GdZQKCMmPANEuFyb",
   "journalEntryId": "muAijyov4VTFfqBL",
   "journalPageId": "FNyaslzj06Ri4wHm"
  },
  {
   "slug": "soithech",
   "name": "Soithech",
   "out": "assets/bestiary/soithech.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "R3CGOnv3X1BQUpB5",
   "journalEntryId": "J0eNyUcWDLD2ornV",
   "journalPageId": "XbjOkmGBMYByEeLN"
  },
  {
   "slug": "ghostly-hounds",
   "name": "Ghostly Hounds",
   "out": "assets/bestiary/ghostly-hounds.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "3WXpoW1ajr2PCDC9",
   "journalEntryId": "6wnyTkZl7GRhVM8g",
   "journalPageId": "6Nw4LldBvZJA3Lm8"
  },
  {
   "slug": "the-pale-hunter",
   "name": "The Pale Hunter",
   "out": "assets/bestiary/the-pale-hunter.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "KEv7LnXs4zQju3lp",
   "journalEntryId": "6wnyTkZl7GRhVM8g",
   "journalPageId": "6Nw4LldBvZJA3Lm8"
  },
  {
   "slug": "skittering-horror",
   "name": "Skittering Horror",
   "out": "assets/bestiary/skittering-horror.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "mk4kCF2buJrsSlK2",
   "journalEntryId": "KcEptvDi3nhRFoBB",
   "journalPageId": "9rYFqciEnJfFIQu8"
  },
  {
   "slug": "star-mole",
   "name": "Star-Mole",
   "out": "assets/bestiary/star-mole.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "89ZjFUUS1I9bP2MH",
   "journalEntryId": "5JC9gQCHQUHugXsQ",
   "journalPageId": "nuJLbTQh1QYWWoTg"
  },
  {
   "slug": "brawzbedr",
   "name": "Brawzbedr",
   "out": "assets/bestiary/brawzbedr.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "eU2PTY1DoA2n95RT",
   "journalEntryId": "sc28aHnwvhvBDyjh",
   "journalPageId": "pAEjZrge0FusCivY"
  },
  {
   "slug": "gouzadn",
   "name": "Gouzadn",
   "out": "assets/bestiary/gouzadn.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "SerJ5gYYlRuUmI9k",
   "journalEntryId": "IS7Y75Kbqe5KILXW",
   "journalPageId": "LO7IdRIzeEGqOvjl"
  },
  {
   "slug": "grochslon",
   "name": "Grochslon",
   "out": "assets/bestiary/grochslon.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "uP9zE6MDiS3TwIWF",
   "journalEntryId": "BUMZ5O0VT9SDjfwE",
   "journalPageId": "zvAUMz9DzP5e9Aec"
  },
  {
   "slug": "corrupted-glasbren",
   "name": "Corrupted Glasbren",
   "out": "assets/bestiary/corrupted-glasbren.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "IornEAAcH3j4YRST",
   "journalEntryId": "g8AKcpFJTeVx51xV",
   "journalPageId": "9ri6PsJH7z67a7UF"
  },
  {
   "slug": "butcherbird",
   "name": "Butcherbird",
   "out": "assets/bestiary/butcherbird.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "dLxI39zRgbt5baD5",
   "journalEntryId": "vuCG2gnrr5slc2Cj",
   "journalPageId": "PSKZl8G6n6RRlEXd"
  },
  {
   "slug": "ceirwmawr",
   "name": "Ceirwmawr",
   "out": "assets/bestiary/ceirwmawr.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "Qe9HW1xQCicVwtGC",
   "journalEntryId": "idLzu8GfQknwWCby",
   "journalPageId": "nal7Fmjmg5Grpcvw"
  },
  {
   "slug": "cynddaraig",
   "name": "Cynddaraig",
   "out": "assets/bestiary/cynddaraig.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "BVvWxKNlDdOzu9Ac",
   "journalEntryId": "JWXOAXD9nd8rkB3I",
   "journalPageId": "oXF62e14JnnztVEB"
  },
  {
   "slug": "feathered-drake",
   "name": "Feathered Drake",
   "out": "assets/bestiary/feathered-drake.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "30NDurP2YczoGj6B",
   "journalEntryId": "T17yRp50eDt8cyXO",
   "journalPageId": "57hELMNqLR2FRrIf"
  },
  {
   "slug": "hagr",
   "name": "Hagr",
   "out": "assets/bestiary/hagr.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "fz8g74CpQcYrqSki",
   "journalEntryId": "ckxdN0P9cHJfsZgQ",
   "journalPageId": "dPV0t98P6gx0ClE8"
  },
  {
   "slug": "nine-fingered-stranger",
   "name": "Nine-Fingered Stranger",
   "out": "assets/bestiary/nine-fingered-stranger.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "Kh5NQGe2zSAEV3BZ",
   "journalEntryId": "SUe3zYQvT9AGKgzG",
   "journalPageId": "m9OXzvC1peHLx1TF"
  },
  {
   "slug": "plasmic-horror",
   "name": "Plasmic Horror",
   "out": "assets/bestiary/plasmic-horror.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "nh6h60KGgx2IlxfF",
   "journalEntryId": "mBQElv2JfT8AW8KH",
   "journalPageId": "jtqfx2ZFWSNH0fpi"
  },
  {
   "slug": "kyakaara",
   "name": "Kyakaara",
   "out": "assets/bestiary/kyakaara.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "Iyc7KUONkBO5Ibyz",
   "journalEntryId": "pOtdFLTTywDCKXPM",
   "journalPageId": "aLuITGoixs7zCyQb"
  },
  {
   "slug": "kleztigr",
   "name": "Kleztigr",
   "out": "assets/bestiary/kleztigr.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "8nNyWAoSsT3VXRx5",
   "journalEntryId": "3e1HimZxPWvqLyu1",
   "journalPageId": "YjdBd1dbn0ZqMdb9"
  },
  {
   "slug": "pack-drake",
   "name": "Pack Drake",
   "out": "assets/bestiary/pack-drake.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "W7YFeowcF0yptQC3",
   "journalEntryId": "Gxjvid2IYJmTU41M",
   "journalPageId": "N96qyRiHh4FbeFhq"
  },
  {
   "slug": "crinwin-broodfather",
   "name": "Crinwin Broodfather",
   "out": "assets/bestiary/crinwin-broodfather.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "hZq0cfLjfytNVrWs",
   "journalEntryId": "Ttz6Fnr2M0HNfIre",
   "journalPageId": "FUyYoLbaxcMQ2XTA"
  },
  {
   "slug": "caralandrao",
   "name": "Caralandrao",
   "out": "assets/bestiary/caralandrao.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "PFHwDgBNwVbZHEIO",
   "journalEntryId": "eAcyCUGDDeqkLrKJ",
   "journalPageId": "cEcM0p8CnQAgBvnd"
  },
  {
   "slug": "wee-folk",
   "name": "Wee Folk",
   "out": "assets/bestiary/wee-folk.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "rL761LrHFjJcfArG",
   "journalEntryId": "aThMYefGFmE0mG73",
   "journalPageId": "wH59rdbyOwJFG5GM"
  },
  {
   "slug": "wild-horse",
   "name": "Wild Horse",
   "out": "assets/bestiary/wild-horse.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "uMjVv3GGJowiNCka",
   "journalEntryId": "nXxqWnbt932F98UJ",
   "journalPageId": "lkhQJa9UPTjB06Dn"
  },
  {
   "slug": "voidblight",
   "name": "Voidblight",
   "out": "assets/bestiary/voidblight.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "P4UPY5CmKLihfSQO",
   "journalEntryId": "smqjMCaaxstHY5nZ",
   "journalPageId": "4ajv8XIGGNNdJZVz"
  },
  {
   "slug": "shaksa",
   "name": "Shaksa",
   "out": "assets/bestiary/shaksa.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "h9IhOM9HBNmdrzUh",
   "journalEntryId": "JK9EeLUOBHfNoHCw",
   "journalPageId": "1JLAhM8J2PwfXZpJ"
  },
  {
   "slug": "hollow-fae",
   "name": "Hollow Fae",
   "out": "assets/bestiary/hollow-fae.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "0ZKo6trYa54afrSZ",
   "journalEntryId": "KgJ8NTJSYfoMhX0Y",
   "journalPageId": "LN7fbBXLMvmCRquV"
  },
  {
   "slug": "frythanc-fledgling",
   "name": "Frythanc Fledgling",
   "out": "assets/bestiary/frythanc-fledgling.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "RGU7Qtp9xioMxQ3k",
   "journalEntryId": "XiAOrP04c2oqpkDg",
   "journalPageId": "e4br5gsUdpBfugGl"
  },
  {
   "slug": "assassin",
   "name": "Assassin",
   "out": "assets/bestiary/assassin.webp",
   "actorPack": "stonetop-pwd.stonetop-bestiary",
   "actorId": "x6X63ArQe1zZ3tBE",
   "journalEntryId": "ew3px3xfQiIpxEtg",
   "journalPageId": "CdxgzGw6aBI3GYEw"
  }
 ],
 "locations": [
  {
   "slug": "the-makers-roads",
   "name": "The Makers' Roads",
   "journalEntryId": "ezquwGFbne6uxzJK",
   "journalPageId": "0J5rrvhCV7xBuIej",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-makers-roads-1.webp"
    }
   ]
  },
  {
   "slug": "the-stream",
   "name": "The Stream",
   "journalEntryId": "KJUzuYlurcjPxHd7",
   "journalPageId": "qg0mwTBbWwCC2bta",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-stream-1.webp"
    }
   ]
  },
  {
   "slug": "waystones",
   "name": "Waystones",
   "journalEntryId": "VrKFDEUbYMEYplMk",
   "journalPageId": "cEPBscFh8D1YRZZn",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/waystones-1.webp"
    }
   ]
  },
  {
   "slug": "blackwater-lake",
   "name": "Blackwater Lake",
   "journalEntryId": "25HD51CKompWLFvB",
   "journalPageId": "fQLW7MZEdD2lPsML",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/blackwater-lake-1.webp"
    }
   ]
  },
  {
   "slug": "ferriers-fen",
   "name": "Ferrier's Fen",
   "journalEntryId": "UstvXnD6EA9IBBO3",
   "journalPageId": "MjRt3VmyHvOLKjkx",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/ferriers-fen-1.webp"
    }
   ]
  },
  {
   "slug": "huffel-peaks",
   "name": "Huffel Peaks",
   "journalEntryId": "RxUdCkI2lL6gE5IH",
   "journalPageId": "g4LGaNLHpQnCjw6E",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/huffel-peaks-1.webp"
    }
   ]
  },
  {
   "slug": "lygos-and-the-south",
   "name": "Lygos & the South",
   "journalEntryId": "DPUvs6Ss8UHXEsCJ",
   "journalPageId": "ZrWwwzUrqugxjDU8",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/lygos-and-the-south-1.webp"
    }
   ]
  },
  {
   "slug": "north-manmarch",
   "name": "North Manmarch",
   "journalEntryId": "NERZ6p7FNc1pxNWL",
   "journalPageId": "5FyaezhZEfD7MSAR",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/north-manmarch-1.webp"
    }
   ]
  },
  {
   "slug": "south-manmarch",
   "name": "South Manmarch",
   "journalEntryId": "apczJSWiu0M5dFrF",
   "journalPageId": "OEmiJvwbFOwASSK3",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/south-manmarch-1.webp"
    }
   ]
  },
  {
   "slug": "the-dread-river",
   "name": "The Dread River",
   "journalEntryId": "lGNIQWIn8CPHuM7E",
   "journalPageId": "rqFWDXswIplr4L8s",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-dread-river-1.webp"
    }
   ]
  },
  {
   "slug": "the-flats",
   "name": "The Flats",
   "journalEntryId": "nBvsH19B1bG2d4Di",
   "journalPageId": "hnfjCiDIWr2QPUuR",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-flats-1.webp"
    }
   ]
  },
  {
   "slug": "the-foothills",
   "name": "The Foothills",
   "journalEntryId": "61j2hjMjANZcniEQ",
   "journalPageId": "HIqfyyRDZUeRduJu",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-foothills-1.webp"
    }
   ]
  },
  {
   "slug": "the-frozen-wastes",
   "name": "The Frozen Wastes",
   "journalEntryId": "xg8MEuSbbEt1wqg8",
   "journalPageId": "UG08UT7YAyN8GoNa",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-frozen-wastes-1.webp"
    }
   ]
  },
  {
   "slug": "the-great-wood",
   "name": "The Great Wood",
   "journalEntryId": "6kt1b8ozEREDCi4k",
   "journalPageId": "OwbdRU0YCyF9qvEC",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-great-wood-1.webp"
    }
   ]
  },
  {
   "slug": "the-labyrinth",
   "name": "The Labyrinth",
   "journalEntryId": "v4slCO5mFJLcZO1q",
   "journalPageId": "0xOQrhcQ8wJFsgjT",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-labyrinth-1.webp"
    }
   ]
  },
  {
   "slug": "the-steplands",
   "name": "The Steplands",
   "journalEntryId": "No8UN1MJEb2mrLXo",
   "journalPageId": "L9aafiUeKDne11Hj",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-steplands-1.webp"
    }
   ]
  },
  {
   "slug": "the-whitefang-mountains",
   "name": "The Whitefang Mountains",
   "journalEntryId": "5vFbBIn18TKtCF91",
   "journalPageId": "9ok9WOFH6pB5E4YF",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-whitefang-mountains-1.webp"
    }
   ]
  },
  {
   "slug": "three-coven-lake",
   "name": "Three Coven Lake",
   "journalEntryId": "zUeBMA1XS4Lq3KdK",
   "journalPageId": "Ol7oAcADxdClvGZw",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/three-coven-lake-1.webp"
    }
   ]
  },
  {
   "slug": "barrier-pass",
   "name": "Barrier Pass",
   "journalEntryId": "VZ3YkXn70E1C7TEO",
   "journalPageId": "DPRYimNgfDixBLBO",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/barrier-pass-1.webp"
    }
   ]
  },
  {
   "slug": "gordins-delve",
   "name": "Gordin's Delve",
   "journalEntryId": "HesP5wBhjA0l9Ffk",
   "journalPageId": "rlqWn9hRa5shvUlY",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/gordins-delve-1.webp"
    }
   ]
  },
  {
   "slug": "marshedge",
   "name": "Marshedge",
   "journalEntryId": "uXlyry9CpXUz4ooR",
   "journalPageId": "TJgCT9BQixIEAHly",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/marshedge-1.webp"
    }
   ]
  },
  {
   "slug": "red-groves",
   "name": "Red Groves",
   "journalEntryId": "o7qpevFfrKXuVlGo",
   "journalPageId": "aAeE7ctFDrQpPARL",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/red-groves-1.webp"
    }
   ]
  },
  {
   "slug": "the-crombil",
   "name": "The Crombil",
   "journalEntryId": "UEQE5cKRurhX9gCE",
   "journalPageId": "mZBuG8teOiJRc49k",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-crombil-1.webp"
    }
   ]
  },
  {
   "slug": "the-golden-oak",
   "name": "The Golden Oak",
   "journalEntryId": "2NsZu7ZKzdrEHfjk",
   "journalPageId": "zK6zVWbEucrqHQs0",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-golden-oak-1.webp"
    }
   ]
  },
  {
   "slug": "the-maw",
   "name": "The Maw",
   "journalEntryId": "vwP9YSr3qrc4Tq7k",
   "journalPageId": "4GEczlSnuypaAiEX",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-maw-1.webp"
    }
   ]
  },
  {
   "slug": "the-ruined-tower",
   "name": "The Ruined Tower",
   "journalEntryId": "iYSktNtms4NQat8F",
   "journalPageId": "3MC797saOr3wnXwd",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-ruined-tower-1.webp"
    }
   ]
  },
  {
   "slug": "the-village-of-stonetop",
   "name": "The Village of Stonetop",
   "journalEntryId": "6yScslDfqrcCQ6CJ",
   "journalPageId": "x2BcdS6EFxG0Ic3F",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-village-of-stonetop-1.webp"
    }
   ]
  },
  {
   "slug": "titan-bones",
   "name": "Titan Bones",
   "journalEntryId": "fc9yqAlxCCgZVckC",
   "journalPageId": "oMNmCXgSQSkxerEK",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/titan-bones-1.webp"
    }
   ]
  },
  {
   "slug": "ustrina",
   "name": "Ustrina",
   "journalEntryId": "MZIqm0QhN3lxNKuO",
   "journalPageId": "B2W00k1wl8ClNwAz",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/ustrina-1.webp"
    }
   ]
  },
  {
   "slug": "vor-svetelik",
   "name": "Vor Svetelik",
   "journalEntryId": "76FKkdtTFxWEGIKQ",
   "journalPageId": "lWEakMs4PwHgcfiW",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/vor-svetelik-1.webp"
    }
   ]
  },
  {
   "slug": "the-things-below",
   "name": "The Things Below",
   "journalEntryId": "5Kym1qDHTmM8XUQ6",
   "journalPageId": "roHUFm71o2upL6Yt",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-things-below.webp"
    }
   ]
  },
  {
   "slug": "the-fae",
   "name": "The Fae",
   "journalEntryId": "Ej5WiMs30baKNXW3",
   "journalPageId": "sgMNDguHzC567bBH",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-fae-1.webp"
    }
   ]
  },
  {
   "slug": "forest-folk",
   "name": "Forest Folk",
   "journalEntryId": "wxslMExj4dQkTPfw",
   "journalPageId": "J79GdwZ5BWnwGW8q",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/forest-folk-1.webp"
    }
   ]
  },
  {
   "slug": "gods-and-religion",
   "name": "Gods & Religion",
   "journalEntryId": "s57tP3Iz6WXkfuJT",
   "journalPageId": "gkcwebWwgIxkEem3",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/gods-and-religion-1.webp"
    }
   ]
  },
  {
   "slug": "green-lords",
   "name": "Green Lords",
   "journalEntryId": "VosjScKksp5B3hsc",
   "journalPageId": "4JhUEFVSapG8Buvc",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/green-lords-1.webp"
    }
   ]
  },
  {
   "slug": "stone-lords",
   "name": "Stone Lords",
   "journalEntryId": "rJiU3RhbILojTC2u",
   "journalPageId": "7b4BpBkwhSdZ8xEN",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/stone-lords-1.webp"
    }
   ]
  },
  {
   "slug": "tempest-lords",
   "name": "Tempest Lords",
   "journalEntryId": "wsIFXTjnJFgO6vnI",
   "journalPageId": "8TvecIdm66GT2hOv",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/tempest-lords-1.webp"
    }
   ]
  },
  {
   "slug": "death-and-the-undying",
   "name": "Death & the Undying",
   "journalEntryId": "CYaQI7gy7RjF0rPH",
   "journalPageId": "EDLSG22jAIZpdwqk",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/death-and-the-undying-3.webp"
    }
   ]
  },
  {
   "slug": "forge-lords",
   "name": "Forge Lords",
   "journalEntryId": "raJkZVRsiVDqsgbj",
   "journalPageId": "08m2XNYH2Ox7Cwaw",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/forge-lords-1.webp"
    }
   ]
  },
  {
   "slug": "spirits-of-the-wild",
   "name": "Spirits of the Wild",
   "journalEntryId": "6v0jqH7HrNvALpjS",
   "journalPageId": "FD49F8IkSOQWgdQd",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/spirits-of-the-wild-1.webp"
    }
   ]
  },
  {
   "slug": "danu-the-earth-mother",
   "name": "Danu, the Earth Mother",
   "journalEntryId": "i0WjzHh0Ugynv2Tl",
   "journalPageId": "ScpAGZvgbKC5U8MR",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/danu-the-earth-mother-1.webp"
    }
   ]
  },
  {
   "slug": "artifact-creation",
   "name": "Artifact Creation",
   "journalEntryId": "mydDNbH6JBlfucco",
   "journalPageId": "D12wCjGr59wFJDZy",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/artifact-creation-1.webp"
    }
   ]
  },
  {
   "slug": "death-and-the-undying",
   "name": "Death & the Undying",
   "journalEntryId": "CYaQI7gy7RjF0rPH",
   "journalPageId": "EDLSG22jAIZpdwqk",
   "sectionIndex": 6,
   "images": [
    {
     "out": "assets/locations/death-and-the-undying-4.webp"
    }
   ]
  },
  {
   "slug": "death-and-the-undying",
   "name": "Death & the Undying",
   "journalEntryId": "CYaQI7gy7RjF0rPH",
   "journalPageId": "EDLSG22jAIZpdwqk",
   "sectionIndex": 5,
   "images": [
    {
     "out": "assets/locations/death-and-the-undying-5.webp"
    }
   ]
  },
  {
   "slug": "death-and-the-undying",
   "name": "Death & the Undying",
   "journalEntryId": "CYaQI7gy7RjF0rPH",
   "journalPageId": "EDLSG22jAIZpdwqk",
   "sectionIndex": 12,
   "images": [
    {
     "out": "assets/locations/death-and-the-undying-6.webp"
    }
   ]
  },
  {
   "slug": "forge-lords",
   "name": "Forge Lords",
   "journalEntryId": "raJkZVRsiVDqsgbj",
   "journalPageId": "08m2XNYH2Ox7Cwaw",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/forge-lords-4.webp"
    }
   ],
   "retired": [
    "assets/locations/forge-lords-6.webp"
   ]
  },
  {
   "slug": "the-golden-oak",
   "name": "The Golden Oak",
   "journalEntryId": "2NsZu7ZKzdrEHfjk",
   "journalPageId": "zK6zVWbEucrqHQs0",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/the-golden-oak-3.webp"
    }
   ]
  },
  {
   "slug": "death-and-the-undying",
   "name": "Death & the Undying",
   "journalEntryId": "CYaQI7gy7RjF0rPH",
   "journalPageId": "EDLSG22jAIZpdwqk",
   "sectionIndex": 1,
   "images": [
    {
     "out": "assets/locations/death-and-the-undying-1.webp"
    }
   ]
  },
  {
   "slug": "the-village-of-stonetop",
   "name": "The Village of Stonetop",
   "journalEntryId": "6yScslDfqrcCQ6CJ",
   "journalPageId": "x2BcdS6EFxG0Ic3F",
   "sectionIndex": 11,
   "images": [
    {
     "out": "assets/locations/the-village-of-stonetop-2.webp"
    }
   ]
  },
  {
   "slug": "the-village-of-stonetop",
   "name": "The Village of Stonetop",
   "journalEntryId": "6yScslDfqrcCQ6CJ",
   "journalPageId": "x2BcdS6EFxG0Ic3F",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/the-village-of-stonetop-3.webp"
    }
   ]
  },
  {
   "slug": "the-village-of-stonetop",
   "name": "The Village of Stonetop",
   "journalEntryId": "6yScslDfqrcCQ6CJ",
   "journalPageId": "x2BcdS6EFxG0Ic3F",
   "sectionIndex": 6,
   "images": [
    {
     "out": "assets/locations/the-village-of-stonetop-4.webp"
    }
   ]
  },
  {
   "slug": "the-village-of-stonetop",
   "name": "The Village of Stonetop",
   "journalEntryId": "6yScslDfqrcCQ6CJ",
   "journalPageId": "x2BcdS6EFxG0Ic3F",
   "sectionIndex": 7,
   "images": [
    {
     "out": "assets/locations/the-village-of-stonetop-5.webp"
    }
   ]
  },
  {
   "slug": "the-village-of-stonetop",
   "name": "The Village of Stonetop",
   "journalEntryId": "6yScslDfqrcCQ6CJ",
   "journalPageId": "x2BcdS6EFxG0Ic3F",
   "sectionIndex": 13,
   "images": [
    {
     "out": "assets/locations/the-village-of-stonetop-6.webp"
    }
   ]
  },
  {
   "slug": "barrier-pass",
   "name": "Barrier Pass",
   "journalEntryId": "VZ3YkXn70E1C7TEO",
   "journalPageId": "DPRYimNgfDixBLBO",
   "sectionIndex": 3,
   "images": [
    {
     "out": "assets/locations/barrier-pass-2.webp"
    }
   ]
  },
  {
   "slug": "barrier-pass",
   "name": "Barrier Pass",
   "journalEntryId": "VZ3YkXn70E1C7TEO",
   "journalPageId": "DPRYimNgfDixBLBO",
   "sectionIndex": 7,
   "images": [
    {
     "out": "assets/locations/barrier-pass-3.webp"
    }
   ]
  },
  {
   "slug": "blackwater-lake",
   "name": "Blackwater Lake",
   "journalEntryId": "25HD51CKompWLFvB",
   "journalPageId": "fQLW7MZEdD2lPsML",
   "sectionIndex": 3,
   "images": [
    {
     "out": "assets/locations/blackwater-lake-2.webp"
    }
   ]
  },
  {
   "slug": "blackwater-lake",
   "name": "Blackwater Lake",
   "journalEntryId": "25HD51CKompWLFvB",
   "journalPageId": "fQLW7MZEdD2lPsML",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/blackwater-lake-3.webp"
    }
   ]
  },
  {
   "slug": "blackwater-lake",
   "name": "Blackwater Lake",
   "journalEntryId": "25HD51CKompWLFvB",
   "journalPageId": "fQLW7MZEdD2lPsML",
   "sectionIndex": 5,
   "images": [
    {
     "out": "assets/locations/blackwater-lake-4.webp"
    }
   ]
  },
  {
   "slug": "death-and-the-undying",
   "name": "Death & the Undying",
   "journalEntryId": "CYaQI7gy7RjF0rPH",
   "journalPageId": "EDLSG22jAIZpdwqk",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/death-and-the-undying-2.webp"
    }
   ]
  },
  {
   "slug": "the-dread-river",
   "name": "The Dread River",
   "journalEntryId": "lGNIQWIn8CPHuM7E",
   "journalPageId": "rqFWDXswIplr4L8s",
   "sectionIndex": 3,
   "images": [
    {
     "out": "assets/locations/the-dread-river-2.webp"
    }
   ]
  },
  {
   "slug": "the-dread-river",
   "name": "The Dread River",
   "journalEntryId": "lGNIQWIn8CPHuM7E",
   "journalPageId": "rqFWDXswIplr4L8s",
   "sectionIndex": 9,
   "images": [
    {
     "out": "assets/locations/the-dread-river-3.webp"
    }
   ]
  },
  {
   "slug": "ferriers-fen",
   "name": "Ferrier's Fen",
   "journalEntryId": "UstvXnD6EA9IBBO3",
   "journalPageId": "MjRt3VmyHvOLKjkx",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/ferriers-fen-2.webp"
    }
   ]
  },
  {
   "slug": "the-flats",
   "name": "The Flats",
   "journalEntryId": "nBvsH19B1bG2d4Di",
   "journalPageId": "hnfjCiDIWr2QPUuR",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/the-flats-2.webp"
    }
   ]
  },
  {
   "slug": "the-flats",
   "name": "The Flats",
   "journalEntryId": "nBvsH19B1bG2d4Di",
   "journalPageId": "hnfjCiDIWr2QPUuR",
   "sectionIndex": 9,
   "images": [
    {
     "out": "assets/locations/the-flats-3.webp"
    }
   ]
  },
  {
   "slug": "the-flats",
   "name": "The Flats",
   "journalEntryId": "nBvsH19B1bG2d4Di",
   "journalPageId": "hnfjCiDIWr2QPUuR",
   "sectionIndex": 5,
   "images": [
    {
     "out": "assets/locations/the-flats-4.webp"
    }
   ]
  },
  {
   "slug": "the-foothills",
   "name": "The Foothills",
   "journalEntryId": "61j2hjMjANZcniEQ",
   "journalPageId": "HIqfyyRDZUeRduJu",
   "sectionIndex": 2,
   "images": [
    {
     "out": "assets/locations/the-foothills-2.webp"
    }
   ]
  },
  {
   "slug": "the-foothills",
   "name": "The Foothills",
   "journalEntryId": "61j2hjMjANZcniEQ",
   "journalPageId": "HIqfyyRDZUeRduJu",
   "sectionIndex": 6,
   "images": [
    {
     "out": "assets/locations/the-foothills-3.webp"
    }
   ]
  },
  {
   "slug": "forge-lords",
   "name": "Forge Lords",
   "journalEntryId": "raJkZVRsiVDqsgbj",
   "journalPageId": "08m2XNYH2Ox7Cwaw",
   "sectionIndex": 3,
   "images": [
    {
     "out": "assets/locations/forge-lords-3.webp"
    }
   ]
  },
  {
   "slug": "gordins-delve",
   "name": "Gordin's Delve",
   "journalEntryId": "HesP5wBhjA0l9Ffk",
   "journalPageId": "rlqWn9hRa5shvUlY",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/gordins-delve-2.webp"
    }
   ]
  },
  {
   "slug": "gordins-delve",
   "name": "Gordin's Delve",
   "journalEntryId": "HesP5wBhjA0l9Ffk",
   "journalPageId": "rlqWn9hRa5shvUlY",
   "sectionIndex": 10,
   "images": [
    {
     "out": "assets/locations/gordins-delve-3.webp"
    }
   ]
  },
  {
   "slug": "gordins-delve",
   "name": "Gordin's Delve",
   "journalEntryId": "HesP5wBhjA0l9Ffk",
   "journalPageId": "rlqWn9hRa5shvUlY",
   "sectionIndex": 11,
   "images": [
    {
     "out": "assets/locations/gordins-delve-4.webp"
    }
   ]
  },
  {
   "slug": "gordins-delve",
   "name": "Gordin's Delve",
   "journalEntryId": "HesP5wBhjA0l9Ffk",
   "journalPageId": "rlqWn9hRa5shvUlY",
   "sectionIndex": 5,
   "images": [
    {
     "out": "assets/locations/gordins-delve-5.webp"
    }
   ]
  },
  {
   "slug": "the-great-wood",
   "name": "The Great Wood",
   "journalEntryId": "6kt1b8ozEREDCi4k",
   "journalPageId": "OwbdRU0YCyF9qvEC",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/the-great-wood-2.webp"
    }
   ]
  },
  {
   "slug": "huffel-peaks",
   "name": "Huffel Peaks",
   "journalEntryId": "RxUdCkI2lL6gE5IH",
   "journalPageId": "g4LGaNLHpQnCjw6E",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/huffel-peaks-2.webp"
    }
   ]
  },
  {
   "slug": "the-labyrinth",
   "name": "The Labyrinth",
   "journalEntryId": "v4slCO5mFJLcZO1q",
   "journalPageId": "0xOQrhcQ8wJFsgjT",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/the-labyrinth-2.webp"
    }
   ]
  },
  {
   "slug": "the-labyrinth",
   "name": "The Labyrinth",
   "journalEntryId": "v4slCO5mFJLcZO1q",
   "journalPageId": "0xOQrhcQ8wJFsgjT",
   "sectionIndex": 6,
   "images": [
    {
     "out": "assets/locations/the-labyrinth-3.webp"
    }
   ]
  },
  {
   "slug": "lygos-and-the-south",
   "name": "Lygos & the South",
   "journalEntryId": "DPUvs6Ss8UHXEsCJ",
   "journalPageId": "ZrWwwzUrqugxjDU8",
   "sectionIndex": 3,
   "images": [
    {
     "out": "assets/locations/lygos-and-the-south-2.webp"
    }
   ]
  },
  {
   "slug": "lygos-and-the-south",
   "name": "Lygos & the South",
   "journalEntryId": "DPUvs6Ss8UHXEsCJ",
   "journalPageId": "ZrWwwzUrqugxjDU8",
   "sectionIndex": 5,
   "images": [
    {
     "out": "assets/locations/lygos-and-the-south-3.webp"
    }
   ]
  },
  {
   "slug": "lygos-and-the-south",
   "name": "Lygos & the South",
   "journalEntryId": "DPUvs6Ss8UHXEsCJ",
   "journalPageId": "ZrWwwzUrqugxjDU8",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/lygos-and-the-south-4.webp"
    }
   ]
  },
  {
   "slug": "lygos-and-the-south",
   "name": "Lygos & the South",
   "journalEntryId": "DPUvs6Ss8UHXEsCJ",
   "journalPageId": "ZrWwwzUrqugxjDU8",
   "sectionIndex": 2,
   "images": [
    {
     "out": "assets/locations/lygos-and-the-south-5.webp"
    }
   ]
  },
  {
   "slug": "the-makers-roads",
   "name": "The Makers' Roads",
   "journalEntryId": "ezquwGFbne6uxzJK",
   "journalPageId": "0J5rrvhCV7xBuIej",
   "sectionIndex": 7,
   "images": [
    {
     "out": "assets/locations/the-makers-roads-2.webp"
    }
   ]
  },
  {
   "slug": "marshedge",
   "name": "Marshedge",
   "journalEntryId": "uXlyry9CpXUz4ooR",
   "journalPageId": "TJgCT9BQixIEAHly",
   "sectionIndex": 9,
   "images": [
    {
     "out": "assets/locations/marshedge-2.webp"
    }
   ]
  },
  {
   "slug": "north-manmarch",
   "name": "North Manmarch",
   "journalEntryId": "NERZ6p7FNc1pxNWL",
   "journalPageId": "5FyaezhZEfD7MSAR",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/north-manmarch-2.webp"
    }
   ]
  },
  {
   "slug": "north-manmarch",
   "name": "North Manmarch",
   "journalEntryId": "NERZ6p7FNc1pxNWL",
   "journalPageId": "5FyaezhZEfD7MSAR",
   "sectionIndex": 9,
   "images": [
    {
     "out": "assets/locations/north-manmarch-3.webp"
    }
   ]
  },
  {
   "slug": "north-manmarch",
   "name": "North Manmarch",
   "journalEntryId": "NERZ6p7FNc1pxNWL",
   "journalPageId": "5FyaezhZEfD7MSAR",
   "sectionIndex": 13,
   "images": [
    {
     "out": "assets/locations/north-manmarch-4.webp"
    }
   ]
  },
  {
   "slug": "the-ruined-tower",
   "name": "The Ruined Tower",
   "journalEntryId": "iYSktNtms4NQat8F",
   "journalPageId": "3MC797saOr3wnXwd",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/the-ruined-tower-2.webp"
    }
   ]
  },
  {
   "slug": "the-ruined-tower",
   "name": "The Ruined Tower",
   "journalEntryId": "iYSktNtms4NQat8F",
   "journalPageId": "3MC797saOr3wnXwd",
   "sectionIndex": 6,
   "images": [
    {
     "out": "assets/locations/the-ruined-tower-3.webp"
    }
   ]
  },
  {
   "slug": "the-ruined-tower",
   "name": "The Ruined Tower",
   "journalEntryId": "iYSktNtms4NQat8F",
   "journalPageId": "3MC797saOr3wnXwd",
   "sectionIndex": 7,
   "images": [
    {
     "out": "assets/locations/the-ruined-tower-4.webp"
    }
   ]
  },
  {
   "slug": "the-steplands",
   "name": "The Steplands",
   "journalEntryId": "No8UN1MJEb2mrLXo",
   "journalPageId": "L9aafiUeKDne11Hj",
   "sectionIndex": 5,
   "images": [
    {
     "out": "assets/locations/the-steplands-2.webp"
    }
   ]
  },
  {
   "slug": "three-coven-lake",
   "name": "Three Coven Lake",
   "journalEntryId": "zUeBMA1XS4Lq3KdK",
   "journalPageId": "Ol7oAcADxdClvGZw",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/three-coven-lake-2.webp"
    }
   ]
  },
  {
   "slug": "vor-svetelik",
   "name": "Vor Svetelik",
   "journalEntryId": "76FKkdtTFxWEGIKQ",
   "journalPageId": "lWEakMs4PwHgcfiW",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/vor-svetelik-2.webp"
    }
   ]
  },
  {
   "slug": "vor-svetelik",
   "name": "Vor Svetelik",
   "journalEntryId": "76FKkdtTFxWEGIKQ",
   "journalPageId": "lWEakMs4PwHgcfiW",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/vor-svetelik-3.webp"
    }
   ]
  },
  {
   "slug": "vor-svetelik",
   "name": "Vor Svetelik",
   "journalEntryId": "76FKkdtTFxWEGIKQ",
   "journalPageId": "lWEakMs4PwHgcfiW",
   "sectionIndex": 6,
   "images": [
    {
     "out": "assets/locations/vor-svetelik-4.webp"
    }
   ]
  },
  {
   "slug": "the-whitefang-mountains",
   "name": "The Whitefang Mountains",
   "journalEntryId": "5vFbBIn18TKtCF91",
   "journalPageId": "9ok9WOFH6pB5E4YF",
   "sectionIndex": 14,
   "images": [
    {
     "out": "assets/locations/the-whitefang-mountains-2.webp"
    }
   ]
  },
  {
   "slug": "rime-lords",
   "name": "Rime Lords",
   "journalEntryId": "oi5Mg2wPABRjvHri",
   "journalPageId": "qq5OueNmkBJjeEKX",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/rime-lords-1.webp"
    }
   ]
  },
  {
   "slug": "forest-folk",
   "name": "Forest Folk",
   "journalEntryId": "wxslMExj4dQkTPfw",
   "journalPageId": "J79GdwZ5BWnwGW8q",
   "sectionIndex": 4,
   "images": [
    {
     "out": "assets/locations/forest-folk-2.webp"
    }
   ]
  },
  {
   "slug": "forge-lords",
   "name": "Forge Lords",
   "journalEntryId": "raJkZVRsiVDqsgbj",
   "journalPageId": "08m2XNYH2Ox7Cwaw",
   "sectionIndex": 1,
   "images": [
    {
     "out": "assets/locations/forge-lords-2.webp"
    }
   ]
  },
  {
   "slug": "forge-lords",
   "name": "Forge Lords",
   "journalEntryId": "raJkZVRsiVDqsgbj",
   "journalPageId": "08m2XNYH2Ox7Cwaw",
   "sectionIndex": 7,
   "images": [
    {
     "out": "assets/locations/forge-lords-5.webp"
    }
   ]
  },
  {
   "slug": "rime-lords",
   "name": "Rime Lords",
   "journalEntryId": "oi5Mg2wPABRjvHri",
   "journalPageId": "qq5OueNmkBJjeEKX",
   "sectionIndex": 3,
   "images": [
    {
     "out": "assets/locations/rime-lords-2.webp"
    }
   ]
  },
  {
   "slug": "rime-lords",
   "name": "Rime Lords",
   "journalEntryId": "oi5Mg2wPABRjvHri",
   "journalPageId": "qq5OueNmkBJjeEKX",
   "sectionIndex": 8,
   "images": [
    {
     "out": "assets/locations/rime-lords-3.webp"
    }
   ]
  },
  {
   "slug": "stone-lords",
   "name": "Stone Lords",
   "journalEntryId": "rJiU3RhbILojTC2u",
   "journalPageId": "7b4BpBkwhSdZ8xEN",
   "sectionIndex": 3,
   "images": [
    {
     "out": "assets/locations/stone-lords-2.webp"
    }
   ]
  },
  {
   "slug": "stone-lords",
   "name": "Stone Lords",
   "journalEntryId": "rJiU3RhbILojTC2u",
   "journalPageId": "7b4BpBkwhSdZ8xEN",
   "sectionIndex": 7,
   "images": [
    {
     "out": "assets/locations/stone-lords-4.webp"
    }
   ]
  },
  {
   "slug": "tempest-lords",
   "name": "Tempest Lords",
   "journalEntryId": "wsIFXTjnJFgO6vnI",
   "journalPageId": "8TvecIdm66GT2hOv",
   "sectionIndex": 3,
   "images": [
    {
     "out": "assets/locations/tempest-lords-2.webp"
    }
   ]
  },
  {
   "slug": "tempest-lords",
   "name": "Tempest Lords",
   "journalEntryId": "wsIFXTjnJFgO6vnI",
   "journalPageId": "8TvecIdm66GT2hOv",
   "sectionIndex": 1,
   "images": [
    {
     "out": "assets/locations/tempest-lords-3.webp"
    }
   ]
  },
  {
   "slug": "tempest-lords",
   "name": "Tempest Lords",
   "journalEntryId": "wsIFXTjnJFgO6vnI",
   "journalPageId": "8TvecIdm66GT2hOv",
   "sectionIndex": 6,
   "images": [
    {
     "out": "assets/locations/tempest-lords-4.webp"
    }
   ]
  },
  {
   "slug": "the-things-below",
   "name": "The Things Below",
   "journalEntryId": "5Kym1qDHTmM8XUQ6",
   "journalPageId": "roHUFm71o2upL6Yt",
   "sectionIndex": 12,
   "images": [
    {
     "out": "assets/locations/the-things-below-2.webp"
    }
   ]
  },
  {
   "slug": "the-things-below",
   "name": "The Things Below",
   "journalEntryId": "5Kym1qDHTmM8XUQ6",
   "journalPageId": "roHUFm71o2upL6Yt",
   "sectionIndex": 6,
   "images": [
    {
     "out": "assets/locations/the-things-below-3.webp"
    }
   ]
  },
  {
   "slug": "the-things-below",
   "name": "The Things Below",
   "journalEntryId": "5Kym1qDHTmM8XUQ6",
   "journalPageId": "roHUFm71o2upL6Yt",
   "sectionIndex": 9,
   "images": [
    {
     "out": "assets/locations/the-things-below-5.webp"
    }
   ]
  },
  {
   "slug": "the-things-below",
   "name": "The Things Below",
   "journalEntryId": "5Kym1qDHTmM8XUQ6",
   "journalPageId": "roHUFm71o2upL6Yt",
   "sectionIndex": 15,
   "images": [
    {
     "out": "assets/locations/the-things-below-6.webp"
    }
   ]
  },
  {
   "slug": "the-things-below",
   "name": "The Things Below",
   "journalEntryId": "5Kym1qDHTmM8XUQ6",
   "journalPageId": "roHUFm71o2upL6Yt",
   "sectionIndex": 10,
   "images": [
    {
     "out": "assets/locations/the-things-below-7.webp"
    }
   ]
  }
 ],
 "settingOverviewMaps": [
  {
   "slug": "book2-vicinity",
   "name": "The Vicinity",
   "out": "assets/maps/book2-vicinity.webp",
   "journalEntryId": "stonetopSO000001",
   "journalPageId": "stonetopSOp00005",
   "replaces": [
    "assets/maps/map-vicinity.webp"
   ]
  },
  {
   "slug": "book2-worlds-end",
   "name": "The World's End",
   "out": "assets/maps/book2-worlds-end.webp",
   "journalEntryId": "stonetopSO000001",
   "journalPageId": "stonetopSOp00010",
   "replaces": [
    "assets/maps/map-worlds-end.webp"
   ]
  },
  {
   "slug": "book2-village-vista",
   "name": "The Village of Stonetop",
   "out": "assets/locations/the-village-of-stonetop-1.webp",
   "journalEntryId": "stonetopSO000001",
   "journalPageId": "stonetopSOp00004",
   "replaces": [
    "assets/maps/map-stonetop-village.webp"
   ]
  }
 ],
 "treasures": [
  {
   "slug": "the-fae-a-pot-of-gold",
   "name": "A pot of “gold”",
   "out": "assets/treasures/the-fae-a-pot-of-gold.webp"
  },
  {
   "slug": "the-fae-the-red-pennant",
   "name": "The Red Pennant",
   "out": "assets/treasures/the-fae-the-red-pennant.webp"
  },
  {
   "slug": "forge-lords-2d4-lumps-of-anthracite",
   "name": "2d4 lumps of anthracite",
   "out": "assets/treasures/forge-lords-2d4-lumps-of-anthracite.webp"
  },
  {
   "slug": "primordial-powers-a-sealed-amphora",
   "name": "A sealed amphora",
   "out": "assets/treasures/primordial-powers-a-sealed-amphora.webp"
  },
  {
   "slug": "the-things-below-a-chunk-of-red-crystal-shaped-to-look-like-a-lee",
   "name": "A chunk of red crystal, shaped to look like a leering skull",
   "out": "assets/treasures/the-things-below-a-chunk-of-red-crystal-shaped-to-look-like-a-lee.webp"
  }
 ],
 "people": [
  {
   "slug": "b1-p135-x526",
   "name": "Book I p.268",
   "out": "assets/people/b1-p135-x526.webp"
  },
  {
   "slug": "b1-p156-x594",
   "name": "Book I p.311",
   "out": "assets/people/b1-p156-x594.webp",
   "presenting": "feminine"
  },
  {
   "slug": "b1-p166-x630",
   "name": "Book I p.331",
   "out": "assets/people/b1-p166-x630.webp"
  },
  {
   "slug": "b1-p267-x987",
   "name": "Book I p.533",
   "out": "assets/people/b1-p267-x987.webp",
   "presenting": "feminine"
  },
  {
   "slug": "b1-p239-x892",
   "name": "Book I p.477",
   "out": "assets/people/b1-p239-x892.webp"
  },
  {
   "slug": "b1-p270-x998",
   "name": "Book I p.539",
   "out": "assets/people/b1-p270-x998.webp",
   "presenting": "feminine"
  },
  {
   "slug": "b2-p031-x121",
   "name": "Book II p.61",
   "out": "assets/people/b2-p031-x121.webp"
  },
  {
   "slug": "b1-p123-x486",
   "name": "Book I p.244",
   "out": "assets/people/b1-p123-x486.webp",
   "presenting": "feminine"
  },
  {
   "slug": "b1-p119-x472",
   "name": "Book I p.237",
   "out": "assets/people/b1-p119-x472.webp",
   "presenting": "feminine"
  },
  {
   "slug": "b1-p103-x420",
   "name": "Book I p.204",
   "out": "assets/people/b1-p103-x420.webp",
   "presenting": "feminine"
  },
  {
   "slug": "b1-p039-x161",
   "name": "Book I p.76",
   "out": "assets/people/b1-p039-x161.webp"
  },
  {
   "slug": "b1-p047-x193",
   "name": "Book I p.92",
   "out": "assets/people/b1-p047-x193.webp"
  },
  {
   "slug": "b1-p007-x32-c750-387-1000-1000",
   "name": "Book I p.12 (detail)",
   "out": "assets/people/b1-p007-x32-c750-387-1000-1000.webp",
   "crop": [
    0.75,
    0.387,
    1,
    1
   ]
  },
  {
   "slug": "b1-p007-x32-c712-116-869-697",
   "name": "Book I p.12 (detail)",
   "out": "assets/people/b1-p007-x32-c712-116-869-697.webp",
   "crop": [
    0.712,
    0.116,
    0.869,
    0.697
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p007-x32-c548-002-719-490",
   "name": "Book I p.12 (detail)",
   "out": "assets/people/b1-p007-x32-c548-002-719-490.webp",
   "crop": [
    0.548,
    0.002,
    0.719,
    0.49
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p007-x32-c335-048-492-452",
   "name": "Book I p.12 (detail)",
   "out": "assets/people/b1-p007-x32-c335-048-492-452.webp",
   "crop": [
    0.335,
    0.048,
    0.492,
    0.452
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p007-x32-c179-000-329-532",
   "name": "Book I p.12 (detail)",
   "out": "assets/people/b1-p007-x32-c179-000-329-532.webp",
   "crop": [
    0.179,
    0,
    0.329,
    0.532
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p007-x32-c000-052-171-552",
   "name": "Book I p.12 (detail)",
   "out": "assets/people/b1-p007-x32-c000-052-171-552.webp",
   "crop": [
    0,
    0.052,
    0.171,
    0.552
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p007-x32-c010-318-210-997",
   "name": "Book I p.12 (detail)",
   "out": "assets/people/b1-p007-x32-c010-318-210-997.webp",
   "crop": [
    0.01,
    0.318,
    0.21,
    0.997
   ]
  },
  {
   "slug": "b1-p007-x32-c169-470-423-1000",
   "name": "Book I p.12 (detail)",
   "out": "assets/people/b1-p007-x32-c169-470-423-1000.webp",
   "crop": [
    0.169,
    0.47,
    0.423,
    1
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p007-x32-c392-463-775-1000",
   "name": "Book I p.12 (detail)",
   "out": "assets/people/b1-p007-x32-c392-463-775-1000.webp",
   "crop": [
    0.392,
    0.463,
    0.775,
    1
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p019-x88-c000-337-348-1000",
   "name": "Book I p.36 (detail)",
   "out": "assets/people/b1-p019-x88-c000-337-348-1000.webp",
   "crop": [
    0,
    0.337,
    0.348,
    1
   ],
   "presenting": "masculine",
   "kid": true
  },
  {
   "slug": "b1-p019-x88-c165-010-450-663",
   "name": "Book I p.36 (detail)",
   "out": "assets/people/b1-p019-x88-c165-010-450-663.webp",
   "crop": [
    0.165,
    0.01,
    0.45,
    0.663
   ],
   "presenting": "feminine",
   "kid": true
  },
  {
   "slug": "b1-p019-x88-c442-003-690-515",
   "name": "Book I p.36 (detail)",
   "out": "assets/people/b1-p019-x88-c442-003-690-515.webp",
   "crop": [
    0.442,
    0.003,
    0.69,
    0.515
   ],
   "presenting": "feminine",
   "kid": true
  },
  {
   "slug": "b1-p019-x88-c631-000-940-633",
   "name": "Book I p.36 (detail)",
   "out": "assets/people/b1-p019-x88-c631-000-940-633.webp",
   "crop": [
    0.631,
    0,
    0.94,
    0.633
   ],
   "kid": true
  },
  {
   "slug": "b1-p019-x88-c502-451-1000-1000",
   "name": "Book I p.36 (detail)",
   "out": "assets/people/b1-p019-x88-c502-451-1000-1000.webp",
   "crop": [
    0.502,
    0.451,
    1,
    1
   ],
   "presenting": "masculine",
   "kid": true
  },
  {
   "slug": "b1-p029-x124-c000-035-489-1000",
   "name": "Book I p.57 (detail)",
   "out": "assets/people/b1-p029-x124-c000-035-489-1000.webp",
   "crop": [
    0,
    0.035,
    0.489,
    1
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p029-x124-c379-000-1000-997",
   "name": "Book I p.57 (detail)",
   "out": "assets/people/b1-p029-x124-c379-000-1000-997.webp",
   "crop": [
    0.379,
    0,
    1,
    0.997
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p032-x134-c052-470-645-1000",
   "name": "Book I p.63 (detail)",
   "out": "assets/people/b1-p032-x134-c052-470-645-1000.webp",
   "crop": [
    0.052,
    0.47,
    0.645,
    1
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p032-x134-c143-172-509-499",
   "name": "Book I p.63 (detail)",
   "out": "assets/people/b1-p032-x134-c143-172-509-499.webp",
   "crop": [
    0.143,
    0.172,
    0.509,
    0.499
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p035-x145-c689-458-929-950",
   "name": "Book I p.68 (detail)",
   "out": "assets/people/b1-p035-x145-c689-458-929-950.webp",
   "crop": [
    0.689,
    0.458,
    0.929,
    0.95
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p035-x145-c117-362-321-976",
   "name": "Book I p.68 (detail)",
   "out": "assets/people/b1-p035-x145-c117-362-321-976.webp",
   "crop": [
    0.117,
    0.362,
    0.321,
    0.976
   ]
  },
  {
   "slug": "b1-p036-x150-c093-000-368-1000",
   "name": "Book I p.71 (detail)",
   "out": "assets/people/b1-p036-x150-c093-000-368-1000.webp",
   "crop": [
    0.093,
    0,
    0.368,
    1
   ]
  },
  {
   "slug": "b1-p036-x150-c362-091-533-875",
   "name": "Book I p.71 (detail)",
   "out": "assets/people/b1-p036-x150-c362-091-533-875.webp",
   "crop": [
    0.362,
    0.091,
    0.533,
    0.875
   ]
  },
  {
   "slug": "b1-p036-x150-c570-057-806-1000",
   "name": "Book I p.71 (detail)",
   "out": "assets/people/b1-p036-x150-c570-057-806-1000.webp",
   "crop": [
    0.57,
    0.057,
    0.806,
    1
   ]
  },
  {
   "slug": "b1-p036-x150-c787-024-997-990",
   "name": "Book I p.71 (detail)",
   "out": "assets/people/b1-p036-x150-c787-024-997-990.webp",
   "crop": [
    0.787,
    0.024,
    0.997,
    0.99
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p036-x150-c510-096-651-880",
   "name": "Book I p.71 (detail)",
   "out": "assets/people/b1-p036-x150-c510-096-651-880.webp",
   "crop": [
    0.51,
    0.096,
    0.651,
    0.88
   ]
  },
  {
   "slug": "b1-p040-x165-c523-143-910-1000",
   "name": "Book I p.79 (detail)",
   "out": "assets/people/b1-p040-x165-c523-143-910-1000.webp",
   "crop": [
    0.523,
    0.143,
    0.91,
    1
   ]
  },
  {
   "slug": "b1-p040-x165-c166-223-441-908",
   "name": "Book I p.79 (detail)",
   "out": "assets/people/b1-p040-x165-c166-223-441-908.webp",
   "crop": [
    0.166,
    0.223,
    0.441,
    0.908
   ]
  },
  {
   "slug": "b1-p040-x165-c298-028-473-717",
   "name": "Book I p.79 (detail)",
   "out": "assets/people/b1-p040-x165-c298-028-473-717.webp",
   "crop": [
    0.298,
    0.028,
    0.473,
    0.717
   ],
   "kid": true
  },
  {
   "slug": "b1-p041-x169-c593-396-941-957",
   "name": "Book I p.80 (detail)",
   "out": "assets/people/b1-p041-x169-c593-396-941-957.webp",
   "crop": [
    0.593,
    0.396,
    0.941,
    0.957
   ]
  },
  {
   "slug": "b1-p041-x169-c483-139-629-721",
   "name": "Book I p.80 (detail)",
   "out": "assets/people/b1-p041-x169-c483-139-629-721.webp",
   "crop": [
    0.483,
    0.139,
    0.629,
    0.721
   ]
  },
  {
   "slug": "b1-p041-x169-c246-461-510-1000",
   "name": "Book I p.80 (detail)",
   "out": "assets/people/b1-p041-x169-c246-461-510-1000.webp",
   "crop": [
    0.246,
    0.461,
    0.51,
    1
   ]
  },
  {
   "slug": "b1-p041-x169-c027-420-214-916",
   "name": "Book I p.80 (detail)",
   "out": "assets/people/b1-p041-x169-c027-420-214-916.webp",
   "crop": [
    0.027,
    0.42,
    0.214,
    0.916
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p041-x169-c268-310-506-639",
   "name": "Book I p.80 (detail)",
   "out": "assets/people/b1-p041-x169-c268-310-506-639.webp",
   "crop": [
    0.268,
    0.31,
    0.506,
    0.639
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p042-x173-c309-000-502-1000",
   "name": "Book I p.82 (detail)",
   "out": "assets/people/b1-p042-x173-c309-000-502-1000.webp",
   "crop": [
    0.309,
    0,
    0.502,
    1
   ]
  },
  {
   "slug": "b1-p042-x173-c000-129-102-839",
   "name": "Book I p.82 (detail)",
   "out": "assets/people/b1-p042-x173-c000-129-102-839.webp",
   "crop": [
    0,
    0.129,
    0.102,
    0.839
   ]
  },
  {
   "slug": "b1-p042-x173-c086-187-180-826",
   "name": "Book I p.82 (detail)",
   "out": "assets/people/b1-p042-x173-c086-187-180-826.webp",
   "crop": [
    0.086,
    0.187,
    0.18,
    0.826
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p042-x173-c161-219-263-819",
   "name": "Book I p.82 (detail)",
   "out": "assets/people/b1-p042-x173-c161-219-263-819.webp",
   "crop": [
    0.161,
    0.219,
    0.263,
    0.819
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p042-x173-c246-143-346-827",
   "name": "Book I p.82 (detail)",
   "out": "assets/people/b1-p042-x173-c246-143-346-827.webp",
   "crop": [
    0.246,
    0.143,
    0.346,
    0.827
   ]
  },
  {
   "slug": "b1-p042-x173-c448-143-598-834",
   "name": "Book I p.82 (detail)",
   "out": "assets/people/b1-p042-x173-c448-143-598-834.webp",
   "crop": [
    0.448,
    0.143,
    0.598,
    0.834
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p042-x173-c546-227-682-846",
   "name": "Book I p.82 (detail)",
   "out": "assets/people/b1-p042-x173-c546-227-682-846.webp",
   "crop": [
    0.546,
    0.227,
    0.682,
    0.846
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p042-x173-c665-098-757-840",
   "name": "Book I p.82 (detail)",
   "out": "assets/people/b1-p042-x173-c665-098-757-840.webp",
   "crop": [
    0.665,
    0.098,
    0.757,
    0.84
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p042-x173-c742-143-857-827",
   "name": "Book I p.82 (detail)",
   "out": "assets/people/b1-p042-x173-c742-143-857-827.webp",
   "crop": [
    0.742,
    0.143,
    0.857,
    0.827
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p042-x173-c838-143-942-846",
   "name": "Book I p.82 (detail)",
   "out": "assets/people/b1-p042-x173-c838-143-942-846.webp",
   "crop": [
    0.838,
    0.143,
    0.942,
    0.846
   ]
  },
  {
   "slug": "b1-p042-x173-c932-208-1000-846",
   "name": "Book I p.82 (detail)",
   "out": "assets/people/b1-p042-x173-c932-208-1000-846.webp",
   "crop": [
    0.932,
    0.208,
    1,
    0.846
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p043-x179-c531-196-710-796",
   "name": "Book I p.85 (detail)",
   "out": "assets/people/b1-p043-x179-c531-196-710-796.webp",
   "crop": [
    0.531,
    0.196,
    0.71,
    0.796
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p043-x179-c687-218-839-569",
   "name": "Book I p.85 (detail)",
   "out": "assets/people/b1-p043-x179-c687-218-839-569.webp",
   "crop": [
    0.687,
    0.218,
    0.839,
    0.569
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p043-x179-c127-391-302-902",
   "name": "Book I p.85 (detail)",
   "out": "assets/people/b1-p043-x179-c127-391-302-902.webp",
   "crop": [
    0.127,
    0.391,
    0.302,
    0.902
   ]
  },
  {
   "slug": "b1-p043-x179-c264-542-469-1000",
   "name": "Book I p.85 (detail)",
   "out": "assets/people/b1-p043-x179-c264-542-469-1000.webp",
   "crop": [
    0.264,
    0.542,
    0.469,
    1
   ]
  },
  {
   "slug": "b1-p043-x179-c314-240-450-716",
   "name": "Book I p.85 (detail)",
   "out": "assets/people/b1-p043-x179-c314-240-450-716.webp",
   "crop": [
    0.314,
    0.24,
    0.45,
    0.716
   ]
  },
  {
   "slug": "b1-p043-x179-c427-290-523-654",
   "name": "Book I p.85 (detail)",
   "out": "assets/people/b1-p043-x179-c427-290-523-654.webp",
   "crop": [
    0.427,
    0.29,
    0.523,
    0.654
   ]
  },
  {
   "slug": "b1-p047-x193-c076-003-465-1000",
   "name": "Book I p.92 (detail)",
   "out": "assets/people/b1-p047-x193-c076-003-465-1000.webp",
   "crop": [
    0.076,
    0.003,
    0.465,
    1
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p088-x364-c193-285-508-965",
   "name": "Book I p.174 (detail)",
   "out": "assets/people/b1-p088-x364-c193-285-508-965.webp",
   "crop": [
    0.193,
    0.285,
    0.508,
    0.965
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p089-x368-c221-247-408-1000",
   "name": "Book I p.177 (detail)",
   "out": "assets/people/b1-p089-x368-c221-247-408-1000.webp",
   "crop": [
    0.221,
    0.247,
    0.408,
    1
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p089-x368-c000-293-221-1000",
   "name": "Book I p.177 (detail)",
   "out": "assets/people/b1-p089-x368-c000-293-221-1000.webp",
   "crop": [
    0,
    0.293,
    0.221,
    1
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p090-x372-c235-039-660-1000",
   "name": "Book I p.178 (detail)",
   "out": "assets/people/b1-p090-x372-c235-039-660-1000.webp",
   "crop": [
    0.235,
    0.039,
    0.66,
    1
   ]
  },
  {
   "slug": "b1-p090-x372-c618-161-993-1000",
   "name": "Book I p.178 (detail)",
   "out": "assets/people/b1-p090-x372-c618-161-993-1000.webp",
   "crop": [
    0.618,
    0.161,
    0.993,
    1
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p090-x372-c000-163-208-997",
   "name": "Book I p.178 (detail)",
   "out": "assets/people/b1-p090-x372-c000-163-208-997.webp",
   "crop": [
    0,
    0.163,
    0.208,
    0.997
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p090-x372-c131-245-333-977",
   "name": "Book I p.178 (detail)",
   "out": "assets/people/b1-p090-x372-c131-245-333-977.webp",
   "crop": [
    0.131,
    0.245,
    0.333,
    0.977
   ]
  },
  {
   "slug": "b1-p092-x380-c002-002-520-1000",
   "name": "Book I p.183 (detail)",
   "out": "assets/people/b1-p092-x380-c002-002-520-1000.webp",
   "crop": [
    0.002,
    0.002,
    0.52,
    1
   ]
  },
  {
   "slug": "b1-p095-x391-c141-290-631-974",
   "name": "Book I p.188 (detail)",
   "out": "assets/people/b1-p095-x391-c141-290-631-974.webp",
   "crop": [
    0.141,
    0.29,
    0.631,
    0.974
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p100-x411-c523-141-837-868",
   "name": "Book I p.199 (detail)",
   "out": "assets/people/b1-p100-x411-c523-141-837-868.webp",
   "crop": [
    0.523,
    0.141,
    0.837,
    0.868
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p100-x411-c060-213-223-881",
   "name": "Book I p.199 (detail)",
   "out": "assets/people/b1-p100-x411-c060-213-223-881.webp",
   "crop": [
    0.06,
    0.213,
    0.223,
    0.881
   ],
   "kid": true
  },
  {
   "slug": "b1-p100-x411-c206-411-362-887",
   "name": "Book I p.199 (detail)",
   "out": "assets/people/b1-p100-x411-c206-411-362-887.webp",
   "crop": [
    0.206,
    0.411,
    0.362,
    0.887
   ],
   "kid": true
  },
  {
   "slug": "b1-p100-x411-c241-226-383-458",
   "name": "Book I p.199 (detail)",
   "out": "assets/people/b1-p100-x411-c241-226-383-458.webp",
   "crop": [
    0.241,
    0.226,
    0.383,
    0.458
   ],
   "kid": true
  },
  {
   "slug": "b1-p107-x435-c504-007-890-853",
   "name": "Book I p.212 (detail)",
   "out": "assets/people/b1-p107-x435-c504-007-890-853.webp",
   "crop": [
    0.504,
    0.007,
    0.89,
    0.853
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p114-x454-c646-207-960-1000",
   "name": "Book I p.227 (detail)",
   "out": "assets/people/b1-p114-x454-c646-207-960-1000.webp",
   "crop": [
    0.646,
    0.207,
    0.96,
    1
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p114-x454-c204-225-621-1000",
   "name": "Book I p.227 (detail)",
   "out": "assets/people/b1-p114-x454-c204-225-621-1000.webp",
   "crop": [
    0.204,
    0.225,
    0.621,
    1
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p114-x454-c000-112-262-1000",
   "name": "Book I p.227 (detail)",
   "out": "assets/people/b1-p114-x454-c000-112-262-1000.webp",
   "crop": [
    0,
    0.112,
    0.262,
    1
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p120-x475-c023-215-496-944",
   "name": "Book I p.238 (detail)",
   "out": "assets/people/b1-p120-x475-c023-215-496-944.webp",
   "crop": [
    0.023,
    0.215,
    0.496,
    0.944
   ]
  },
  {
   "slug": "b1-p124-x490-c050-297-609-859",
   "name": "Book I p.247 (detail)",
   "out": "assets/people/b1-p124-x490-c050-297-609-859.webp",
   "crop": [
    0.05,
    0.297,
    0.609,
    0.859
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p124-x490-c350-000-855-436",
   "name": "Book I p.247 (detail)",
   "out": "assets/people/b1-p124-x490-c350-000-855-436.webp",
   "crop": [
    0.35,
    0,
    0.855,
    0.436
   ]
  },
  {
   "slug": "b1-p124-x490-c395-334-1000-1000",
   "name": "Book I p.247 (detail)",
   "out": "assets/people/b1-p124-x490-c395-334-1000-1000.webp",
   "crop": [
    0.395,
    0.334,
    1,
    1
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p134-x521-c125-064-776-651",
   "name": "Book I p.267 (detail)",
   "out": "assets/people/b1-p134-x521-c125-064-776-651.webp",
   "crop": [
    0.125,
    0.064,
    0.776,
    0.651
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p134-x521-c451-368-1000-1000",
   "name": "Book I p.267 (detail)",
   "out": "assets/people/b1-p134-x521-c451-368-1000-1000.webp",
   "crop": [
    0.451,
    0.368,
    1,
    1
   ]
  },
  {
   "slug": "b1-p137-x533-c000-012-229-1000",
   "name": "Book I p.272 (detail)",
   "out": "assets/people/b1-p137-x533-c000-012-229-1000.webp",
   "crop": [
    0,
    0.012,
    0.229,
    1
   ]
  },
  {
   "slug": "b1-p137-x533-c187-035-393-1000",
   "name": "Book I p.272 (detail)",
   "out": "assets/people/b1-p137-x533-c187-035-393-1000.webp",
   "crop": [
    0.187,
    0.035,
    0.393,
    1
   ]
  },
  {
   "slug": "b1-p137-x533-c352-016-581-1000",
   "name": "Book I p.272 (detail)",
   "out": "assets/people/b1-p137-x533-c352-016-581-1000.webp",
   "crop": [
    0.352,
    0.016,
    0.581,
    1
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p137-x533-c541-004-810-1000",
   "name": "Book I p.272 (detail)",
   "out": "assets/people/b1-p137-x533-c541-004-810-1000.webp",
   "crop": [
    0.541,
    0.004,
    0.81,
    1
   ]
  },
  {
   "slug": "b1-p137-x533-c754-024-999-1000",
   "name": "Book I p.272 (detail)",
   "out": "assets/people/b1-p137-x533-c754-024-999-1000.webp",
   "crop": [
    0.754,
    0.024,
    0.999,
    1
   ]
  },
  {
   "slug": "b1-p150-x573-c442-213-810-1000",
   "name": "Book I p.299 (detail)",
   "out": "assets/people/b1-p150-x573-c442-213-810-1000.webp",
   "crop": [
    0.442,
    0.213,
    0.81,
    1
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p150-x573-c129-235-369-1000",
   "name": "Book I p.299 (detail)",
   "out": "assets/people/b1-p150-x573-c129-235-369-1000.webp",
   "crop": [
    0.129,
    0.235,
    0.369,
    1
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p150-x573-c000-036-196-1000",
   "name": "Book I p.299 (detail)",
   "out": "assets/people/b1-p150-x573-c000-036-196-1000.webp",
   "crop": [
    0,
    0.036,
    0.196,
    1
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p154-x587-c029-001-496-1000",
   "name": "Book I p.307 (detail)",
   "out": "assets/people/b1-p154-x587-c029-001-496-1000.webp",
   "crop": [
    0.029,
    0.001,
    0.496,
    1
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p154-x587-c459-000-996-996",
   "name": "Book I p.307 (detail)",
   "out": "assets/people/b1-p154-x587-c459-000-996-996.webp",
   "crop": [
    0.459,
    0,
    0.996,
    0.996
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p169-x640-c252-113-982-983",
   "name": "Book I p.336 (detail)",
   "out": "assets/people/b1-p169-x640-c252-113-982-983.webp",
   "crop": [
    0.252,
    0.113,
    0.982,
    0.983
   ]
  },
  {
   "slug": "b1-p169-x640-c094-103-346-661",
   "name": "Book I p.336 (detail)",
   "out": "assets/people/b1-p169-x640-c094-103-346-661.webp",
   "crop": [
    0.094,
    0.103,
    0.346,
    0.661
   ]
  },
  {
   "slug": "b1-p174-x658-c558-074-741-615",
   "name": "Book I p.347 (detail)",
   "out": "assets/people/b1-p174-x658-c558-074-741-615.webp",
   "crop": [
    0.558,
    0.074,
    0.741,
    0.615
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p174-x658-c718-047-889-592",
   "name": "Book I p.347 (detail)",
   "out": "assets/people/b1-p174-x658-c718-047-889-592.webp",
   "crop": [
    0.718,
    0.047,
    0.889,
    0.592
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p192-x723-c114-124-508-580",
   "name": "Book I p.383 (detail)",
   "out": "assets/people/b1-p192-x723-c114-124-508-580.webp",
   "crop": [
    0.114,
    0.124,
    0.508,
    0.58
   ]
  },
  {
   "slug": "b1-p195-x731-c350-272-566-1000",
   "name": "Book I p.389 (detail)",
   "out": "assets/people/b1-p195-x731-c350-272-566-1000.webp",
   "crop": [
    0.35,
    0.272,
    0.566,
    1
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p195-x731-c193-230-408-1000",
   "name": "Book I p.389 (detail)",
   "out": "assets/people/b1-p195-x731-c193-230-408-1000.webp",
   "crop": [
    0.193,
    0.23,
    0.408,
    1
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p195-x731-c004-323-156-1000",
   "name": "Book I p.389 (detail)",
   "out": "assets/people/b1-p195-x731-c004-323-156-1000.webp",
   "crop": [
    0.004,
    0.323,
    0.156,
    1
   ]
  },
  {
   "slug": "b1-p195-x731-c108-327-237-982",
   "name": "Book I p.389 (detail)",
   "out": "assets/people/b1-p195-x731-c108-327-237-982.webp",
   "crop": [
    0.108,
    0.327,
    0.237,
    0.982
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p204-x772-c450-000-706-1000",
   "name": "Book I p.407 (detail)",
   "out": "assets/people/b1-p204-x772-c450-000-706-1000.webp",
   "crop": [
    0.45,
    0,
    0.706,
    1
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p204-x772-c683-006-944-1000",
   "name": "Book I p.407 (detail)",
   "out": "assets/people/b1-p204-x772-c683-006-944-1000.webp",
   "crop": [
    0.683,
    0.006,
    0.944,
    1
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p208-x784-c674-037-874-916",
   "name": "Book I p.415 (detail)",
   "out": "assets/people/b1-p208-x784-c674-037-874-916.webp",
   "crop": [
    0.674,
    0.037,
    0.874,
    0.916
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p208-x784-c467-230-694-785",
   "name": "Book I p.415 (detail)",
   "out": "assets/people/b1-p208-x784-c467-230-694-785.webp",
   "crop": [
    0.467,
    0.23,
    0.694,
    0.785
   ]
  },
  {
   "slug": "b1-p208-x784-c167-178-376-942",
   "name": "Book I p.415 (detail)",
   "out": "assets/people/b1-p208-x784-c167-178-376-942.webp",
   "crop": [
    0.167,
    0.178,
    0.376,
    0.942
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p209-x792-c086-000-497-1000",
   "name": "Book I p.416 (detail)",
   "out": "assets/people/b1-p209-x792-c086-000-497-1000.webp",
   "crop": [
    0.086,
    0,
    0.497,
    1
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p209-x792-c427-005-881-805",
   "name": "Book I p.416 (detail)",
   "out": "assets/people/b1-p209-x792-c427-005-881-805.webp",
   "crop": [
    0.427,
    0.005,
    0.881,
    0.805
   ]
  },
  {
   "slug": "b1-p209-x792-c680-241-1000-745",
   "name": "Book I p.416 (detail)",
   "out": "assets/people/b1-p209-x792-c680-241-1000-745.webp",
   "crop": [
    0.68,
    0.241,
    1,
    0.745
   ]
  },
  {
   "slug": "b1-p211-x800-c000-007-443-1000",
   "name": "Book I p.421 (detail)",
   "out": "assets/people/b1-p211-x800-c000-007-443-1000.webp",
   "crop": [
    0,
    0.007,
    0.443,
    1
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p211-x800-c412-000-1000-995",
   "name": "Book I p.421 (detail)",
   "out": "assets/people/b1-p211-x800-c412-000-1000-995.webp",
   "crop": [
    0.412,
    0,
    1,
    0.995
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p212-x803-c508-267-954-1000",
   "name": "Book I p.422 (detail)",
   "out": "assets/people/b1-p212-x803-c508-267-954-1000.webp",
   "crop": [
    0.508,
    0.267,
    0.954,
    1
   ]
  },
  {
   "slug": "b1-p212-x803-c223-316-408-725",
   "name": "Book I p.422 (detail)",
   "out": "assets/people/b1-p212-x803-c223-316-408-725.webp",
   "crop": [
    0.223,
    0.316,
    0.408,
    0.725
   ]
  },
  {
   "slug": "b1-p216-x816-c033-006-475-990",
   "name": "Book I p.431 (detail)",
   "out": "assets/people/b1-p216-x816-c033-006-475-990.webp",
   "crop": [
    0.033,
    0.006,
    0.475,
    0.99
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p216-x816-c452-000-942-978",
   "name": "Book I p.431 (detail)",
   "out": "assets/people/b1-p216-x816-c452-000-942-978.webp",
   "crop": [
    0.452,
    0,
    0.942,
    0.978
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p217-x820-c448-005-967-1000",
   "name": "Book I p.432 (detail)",
   "out": "assets/people/b1-p217-x820-c448-005-967-1000.webp",
   "crop": [
    0.448,
    0.005,
    0.967,
    1
   ]
  },
  {
   "slug": "b1-p217-x820-c079-105-411-1000",
   "name": "Book I p.432 (detail)",
   "out": "assets/people/b1-p217-x820-c079-105-411-1000.webp",
   "crop": [
    0.079,
    0.105,
    0.411,
    1
   ]
  },
  {
   "slug": "b1-p230-x864-c075-032-496-1000",
   "name": "Book I p.459 (detail)",
   "out": "assets/people/b1-p230-x864-c075-032-496-1000.webp",
   "crop": [
    0.075,
    0.032,
    0.496,
    1
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p230-x864-c458-000-894-998",
   "name": "Book I p.459 (detail)",
   "out": "assets/people/b1-p230-x864-c458-000-894-998.webp",
   "crop": [
    0.458,
    0,
    0.894,
    0.998
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p241-x899-c000-023-252-1000",
   "name": "Book I p.481 (detail)",
   "out": "assets/people/b1-p241-x899-c000-023-252-1000.webp",
   "crop": [
    0,
    0.023,
    0.252,
    1
   ]
  },
  {
   "slug": "b1-p241-x899-c742-089-877-688",
   "name": "Book I p.481 (detail)",
   "out": "assets/people/b1-p241-x899-c742-089-877-688.webp",
   "crop": [
    0.742,
    0.089,
    0.877,
    0.688
   ]
  },
  {
   "slug": "b1-p246-x915-c693-402-820-991",
   "name": "Book I p.490 (detail)",
   "out": "assets/people/b1-p246-x915-c693-402-820-991.webp",
   "crop": [
    0.693,
    0.402,
    0.82,
    0.991
   ],
   "kid": true
  },
  {
   "slug": "b1-p246-x915-c566-301-724-1000",
   "name": "Book I p.490 (detail)",
   "out": "assets/people/b1-p246-x915-c566-301-724-1000.webp",
   "crop": [
    0.566,
    0.301,
    0.724,
    1
   ],
   "kid": true
  },
  {
   "slug": "b1-p246-x915-c501-307-605-932",
   "name": "Book I p.490 (detail)",
   "out": "assets/people/b1-p246-x915-c501-307-605-932.webp",
   "crop": [
    0.501,
    0.307,
    0.605,
    0.932
   ],
   "kid": true
  },
  {
   "slug": "b1-p246-x915-c324-080-537-985",
   "name": "Book I p.490 (detail)",
   "out": "assets/people/b1-p246-x915-c324-080-537-985.webp",
   "crop": [
    0.324,
    0.08,
    0.537,
    0.985
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p246-x915-c000-233-201-1000",
   "name": "Book I p.490 (detail)",
   "out": "assets/people/b1-p246-x915-c000-233-201-1000.webp",
   "crop": [
    0,
    0.233,
    0.201,
    1
   ],
   "kid": true
  },
  {
   "slug": "b1-p246-x915-c151-001-345-1000",
   "name": "Book I p.490 (detail)",
   "out": "assets/people/b1-p246-x915-c151-001-345-1000.webp",
   "crop": [
    0.151,
    0.001,
    0.345,
    1
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p257-x953-c000-000-506-1000",
   "name": "Book I p.512 (detail)",
   "out": "assets/people/b1-p257-x953-c000-000-506-1000.webp",
   "crop": [
    0,
    0,
    0.506,
    1
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p257-x953-c262-349-433-944",
   "name": "Book I p.512 (detail)",
   "out": "assets/people/b1-p257-x953-c262-349-433-944.webp",
   "crop": [
    0.262,
    0.349,
    0.433,
    0.944
   ]
  },
  {
   "slug": "b1-p261-x969-c529-452-856-1000",
   "name": "Book I p.520 (detail)",
   "out": "assets/people/b1-p261-x969-c529-452-856-1000.webp",
   "crop": [
    0.529,
    0.452,
    0.856,
    1
   ]
  },
  {
   "slug": "b1-p261-x969-c027-533-196-983",
   "name": "Book I p.520 (detail)",
   "out": "assets/people/b1-p261-x969-c027-533-196-983.webp",
   "crop": [
    0.027,
    0.533,
    0.196,
    0.983
   ]
  },
  {
   "slug": "b1-p261-x969-c254-570-504-986",
   "name": "Book I p.520 (detail)",
   "out": "assets/people/b1-p261-x969-c254-570-504-986.webp",
   "crop": [
    0.254,
    0.57,
    0.504,
    0.986
   ]
  },
  {
   "slug": "b1-p268-x990-c393-103-1000-1000",
   "name": "Book I p.535 (detail)",
   "out": "assets/people/b1-p268-x990-c393-103-1000-1000.webp",
   "crop": [
    0.393,
    0.103,
    1,
    1
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p268-x990-c000-001-499-1000",
   "name": "Book I p.535 (detail)",
   "out": "assets/people/b1-p268-x990-c000-001-499-1000.webp",
   "crop": [
    0,
    0.001,
    0.499,
    1
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p270-x996-c281-002-625-992",
   "name": "Book I p.538 (detail)",
   "out": "assets/people/b1-p270-x996-c281-002-625-992.webp",
   "crop": [
    0.281,
    0.002,
    0.625,
    0.992
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p270-x996-c606-122-842-929",
   "name": "Book I p.538 (detail)",
   "out": "assets/people/b1-p270-x996-c606-122-842-929.webp",
   "crop": [
    0.606,
    0.122,
    0.842,
    0.929
   ]
  },
  {
   "slug": "b1-p270-x996-c773-074-998-907",
   "name": "Book I p.538 (detail)",
   "out": "assets/people/b1-p270-x996-c773-074-998-907.webp",
   "crop": [
    0.773,
    0.074,
    0.998,
    0.907
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p275-x1013-c000-239-501-1000",
   "name": "Book I p.549 (detail)",
   "out": "assets/people/b1-p275-x1013-c000-239-501-1000.webp",
   "crop": [
    0,
    0.239,
    0.501,
    1
   ]
  },
  {
   "slug": "b1-p275-x1013-c439-111-1000-1000",
   "name": "Book I p.549 (detail)",
   "out": "assets/people/b1-p275-x1013-c439-111-1000-1000.webp",
   "crop": [
    0.439,
    0.111,
    1,
    1
   ]
  },
  {
   "slug": "b1-p287-x1051-c129-782-318-1000",
   "name": "Book I p.573 (detail)",
   "out": "assets/people/b1-p287-x1051-c129-782-318-1000.webp",
   "crop": [
    0.129,
    0.782,
    0.318,
    1
   ],
   "kid": true
  },
  {
   "slug": "b1-p287-x1051-c289-812-429-1000",
   "name": "Book I p.573 (detail)",
   "out": "assets/people/b1-p287-x1051-c289-812-429-1000.webp",
   "crop": [
    0.289,
    0.812,
    0.429,
    1
   ],
   "kid": true
  },
  {
   "slug": "b1-p294-x1074-c000-186-606-1000",
   "name": "Book I p.586 (detail)",
   "out": "assets/people/b1-p294-x1074-c000-186-606-1000.webp",
   "crop": [
    0,
    0.186,
    0.606,
    1
   ],
   "presenting": "feminine"
  },
  {
   "slug": "b1-p294-x1074-c514-133-1000-996",
   "name": "Book I p.586 (detail)",
   "out": "assets/people/b1-p294-x1074-c514-133-1000-996.webp",
   "crop": [
    0.514,
    0.133,
    1,
    0.996
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b1-p297-x1085-c242-046-546-1000",
   "name": "Book I p.593 (detail)",
   "out": "assets/people/b1-p297-x1085-c242-046-546-1000.webp",
   "crop": [
    0.242,
    0.046,
    0.546,
    1
   ]
  },
  {
   "slug": "b1-p297-x1085-c421-219-775-1000",
   "name": "Book I p.593 (detail)",
   "out": "assets/people/b1-p297-x1085-c421-219-775-1000.webp",
   "crop": [
    0.421,
    0.219,
    0.775,
    1
   ],
   "presenting": "masculine"
  },
  {
   "slug": "b2-p020-x76-c235-192-695-981",
   "name": "Book II p.38 (detail)",
   "out": "assets/people/b2-p020-x76-c235-192-695-981.webp",
   "crop": [
    0.235,
    0.192,
    0.695,
    0.981
   ]
  },
  {
   "slug": "b2-p020-x76-c583-237-868-736",
   "name": "Book II p.38 (detail)",
   "out": "assets/people/b2-p020-x76-c583-237-868-736.webp",
   "crop": [
    0.583,
    0.237,
    0.868,
    0.736
   ]
  },
  {
   "slug": "b2-p092-x361-c046-000-402-1000",
   "name": "Book II p.183 (detail)",
   "out": "assets/people/b2-p092-x361-c046-000-402-1000.webp",
   "crop": [
    0.046,
    0,
    0.402,
    1
   ]
  },
  {
   "slug": "b2-p135-x539-c200-263-596-1000",
   "name": "Book II p.269 (detail)",
   "out": "assets/people/b2-p135-x539-c200-263-596-1000.webp",
   "crop": [
    0.2,
    0.263,
    0.596,
    1
   ]
  },
  {
   "slug": "b2-p154-x619-c502-236-646-658",
   "name": "Book II p.306 (detail)",
   "out": "assets/people/b2-p154-x619-c502-236-646-658.webp",
   "crop": [
    0.502,
    0.236,
    0.646,
    0.658
   ]
  },
  {
   "slug": "b2-p154-x619-c025-533-365-1000",
   "name": "Book II p.306 (detail)",
   "out": "assets/people/b2-p154-x619-c025-533-365-1000.webp",
   "crop": [
    0.025,
    0.533,
    0.365,
    1
   ]
  }
 ],
 "codex": [
  {
   "journalEntryId": "5tvhzovmN18QlxGa",
   "journalPageId": "TGra87VIxIOJstZX",
   "name": "Yaarowslow, the Many",
   "managed": [
    "assets/bestiary/yaarowslow-the-many.webp",
    "assets/bestiary/swarm-of-silvery-vermin.webp"
   ],
   "slots": [
    {
     "slot": "banner",
     "images": [
      {
       "out": "assets/bestiary/yaarowslow-the-many.webp",
       "name": "Yaarowslow, the Many"
      }
     ]
    }
   ]
  },
  {
   "journalEntryId": "VJDP2ETcmA8GeHdT",
   "journalPageId": "5mYNP79ZxnvKJ8pB",
   "name": "Horned Drake",
   "managed": [
    "assets/bestiary/horned-drake.webp",
    "assets/bestiary/horned-drake-young.webp"
   ],
   "slots": [
    {
     "slot": "banner",
     "images": [
      {
       "out": "assets/bestiary/horned-drake.webp",
       "name": "Horned Drake"
      }
     ]
    }
   ]
  }
 ],
 "steadings": [
  {
   "slug": "stonetop-steading",
   "name": "Stonetop",
   "out": "assets/steading/stonetop.webp"
  }
 ]
};
