// AUTO-GENERATED by scripts/local/book2-art/gen-pack-macro.js from manifest.json.
// Do NOT edit by hand. Slim apply-only manifest: just the fields the running system
// needs to re-point compendium/world documents at the durable Book II art on disk
// (no PDF geometry). Consumed by module/book2-art/reapply.js. Regenerate with:
//   node scripts/local/book2-art/gen-pack-macro.js

export const BOOK2_ART_APPLY_MANIFEST = {
 "monsters": [
  {
   "slug": "crinwin",
   "name": "Crinwin",
   "out": "assets/bestiary/crinwin.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "F0SuxRtw6dqB6Nvh",
   "journalEntryId": "Ttz6Fnr2M0HNfIre",
   "journalPageId": "FUyYoLbaxcMQ2XTA"
  },
  {
   "slug": "myghal",
   "name": "Myghal, Deathless Sorcerer",
   "out": "assets/bestiary/myghal.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "xSrPam8ZFxg24LQl",
   "journalEntryId": "fhCGhdK4KZ5fBsUL",
   "journalPageId": "NadumFaGYEX4NSc0"
  },
  {
   "slug": "phantom-rider",
   "name": "Phantom Rider",
   "out": "assets/bestiary/phantom-rider.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "8T8jqS04adlc5107",
   "journalEntryId": "llEqxrhsKD2DvYdP",
   "journalPageId": "ccg4Fpzc9VeL0gBK"
  },
  {
   "slug": "servants-of-daagon",
   "name": "Servant of Daagon",
   "out": "assets/bestiary/servants-of-daagon.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "BCA8xC2gsvHO43ou",
   "journalEntryId": "SmHddXJMWp3niCln",
   "journalPageId": "EEIU9yPFNldtPXAZ"
  },
  {
   "slug": "necromancer",
   "name": "Necromancer",
   "out": "assets/bestiary/necromancer.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "58UtB8l8G68t9nRI",
   "journalEntryId": "9MF7xia8nqIu1V8N",
   "journalPageId": "DZU7wBHDfNukWLs1"
  },
  {
   "slug": "gwraig-wen",
   "name": "The Gwraig Wen",
   "out": "assets/bestiary/gwraig-wen.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "B0W8jT7lRFLJK4ds",
   "journalEntryId": "i74FkC9ROlheQBIF",
   "journalPageId": "28Ko2NCItg3Bfkf9"
  },
  {
   "slug": "willow-witches",
   "name": "Willow Witches",
   "out": "assets/bestiary/willow-witches.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "q6EfKl09RA6NKWEc",
   "journalEntryId": "M8gYXMHKcRqCshbC",
   "journalPageId": "2hPfGCxCxK6zS7th"
  },
  {
   "slug": "draventao",
   "name": "Draventao",
   "out": "assets/bestiary/draventao.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "9kcSzC3uPavigsyF",
   "journalEntryId": "sKYvwXBCiWfqNZlU",
   "journalPageId": "MxnVw08jIaPKl8MP"
  },
  {
   "slug": "llamudwr",
   "name": "Llamudwr",
   "out": "assets/bestiary/llamudwr.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "zWFuS69kPihbwlKp",
   "journalEntryId": "7qfPIuaRwuUPi4nV",
   "journalPageId": "R2kOFklneqKTwTWd"
  },
  {
   "slug": "mummified-green-lord",
   "name": "Mummified Green Lord",
   "out": "assets/bestiary/mummified-green-lord.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "TGLFOv8AqB8gHXvM",
   "journalEntryId": "EwO2lHfT38Fi7uqK",
   "journalPageId": "J8A6ThARz2TEegEV"
  },
  {
   "slug": "mummified-servant",
   "name": "Mummified Servant",
   "out": "assets/bestiary/mummified-servant.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "WVBxp5Ii2Ahd6Xln",
   "journalEntryId": "bO6QXFMmtAmKL3zO",
   "journalPageId": "ynEVoraTg5NZAlmU"
  },
  {
   "slug": "zrajedak",
   "name": "Zrajedak",
   "out": "assets/bestiary/zrajedak.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "3JaMhYyy0qDzf06q",
   "journalEntryId": "CGPfnYi6Y86dEdE0",
   "journalPageId": "vyDWFkK5vBnfGLZS"
  },
  {
   "slug": "hdour",
   "name": "Hdour",
   "out": "assets/bestiary/hdour.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "Okqc6kkhEZ3CGYKl",
   "journalEntryId": "Owbdgx7wi7p30MzW",
   "journalPageId": "yvKK2IoV4vk8Z8Dp"
  },
  {
   "slug": "hillfolk-rider",
   "name": "Hillfolk Rider",
   "out": "assets/bestiary/hillfolk-rider.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "05mh4Ag0uKxRVY8j",
   "journalEntryId": "J3KbSweAhRZfonEX",
   "journalPageId": "XwlDiMYnCmrH0CCc"
  },
  {
   "slug": "spirit-talker",
   "name": "Spirit-talker",
   "out": "assets/bestiary/spirit-talker.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "7ID9ieGRtwH4QoE8",
   "journalEntryId": "nJnOuEaIJBZParuZ",
   "journalPageId": "lqG9EkFDvTaGUVR1"
  },
  {
   "slug": "adventurer",
   "name": "Adventurer",
   "out": "assets/bestiary/adventurer.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "aAknV9EMnUjJvRL3",
   "journalEntryId": "mqbnYBt53E6uF73P",
   "journalPageId": "EAzIkasPD1rTWc2G"
  },
  {
   "slug": "antiquarian",
   "name": "Antiquarian",
   "out": "assets/bestiary/antiquarian.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "bZKtYZmapDExeAJU",
   "journalEntryId": "T1ELDbVtepRKsf3d",
   "journalPageId": "PSYUphUQPJtiNl0C"
  },
  {
   "slug": "caravan-guard",
   "name": "Caravan Guard",
   "out": "assets/bestiary/caravan-guard.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "rmNfHJdCkFfrBVIL",
   "journalEntryId": "eLDyz1PDrdPnbnG9",
   "journalPageId": "ltv7WDfMzG1MFpho"
  },
  {
   "slug": "infantry",
   "name": "Infantry",
   "out": "assets/bestiary/infantry.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "r5Ea7yfpDcp6WTO4",
   "journalEntryId": "RrC8q9cFYtODqipS",
   "journalPageId": "XN6JjsXaKtAGdhJR"
  },
  {
   "slug": "shantyara",
   "name": "Shantyara",
   "out": "assets/bestiary/shantyara.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "j8rFoANTmTHD5MKF",
   "journalEntryId": "5Sv77XzHPMBgZqJZ",
   "journalPageId": "wpyE6SCPfsbzsAj7"
  },
  {
   "slug": "fundamental",
   "name": "Fundamental",
   "out": "assets/bestiary/fundamental.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "iPBB5qDX5urJ30FU",
   "journalEntryId": "WObWuLHBHqBYlZlA",
   "journalPageId": "x2kSq3GwFhREPjAS"
  },
  {
   "slug": "the-nightingale",
   "name": "The Nightingale",
   "out": "assets/bestiary/the-nightingale.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "9h3AbAG1DBQTrtOG",
   "journalEntryId": "aGS4afk7P2DhhFN0",
   "journalPageId": "NOZWTnGdb2tXHzgM"
  },
  {
   "slug": "rime-lord",
   "name": "Rime Lord",
   "out": "assets/bestiary/rime-lord.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "knIBykmqBqa8lMFN",
   "journalEntryId": "lMOwbXpvkp9KL5SG",
   "journalPageId": "mVZaaOE7Ih4T3CNt"
  },
  {
   "slug": "horned-drake-young",
   "name": "Horned Drake (Young)",
   "out": "assets/bestiary/horned-drake-young.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "MmkSpS99xDX01jeC",
   "journalEntryId": "VJDP2ETcmA8GeHdT",
   "journalPageId": "5mYNP79ZxnvKJ8pB"
  },
  {
   "slug": "horned-drake",
   "name": "Horned Drake",
   "out": "assets/bestiary/horned-drake.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "XFmKN7n1uddyo55m",
   "journalEntryId": "VJDP2ETcmA8GeHdT",
   "journalPageId": "5mYNP79ZxnvKJ8pB"
  },
  {
   "slug": "coedwaig",
   "name": "Coedwaig",
   "out": "assets/bestiary/coedwaig.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "Hogu0AEnAffI0HHr",
   "journalEntryId": "4cuy0KcuT5WO0S5A",
   "journalPageId": "IwC0rnZcM22Hkn5D"
  },
  {
   "slug": "grwgnach",
   "name": "Grwgnach",
   "out": "assets/bestiary/grwgnach.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "QJzjWDCU8jAAb4DT",
   "journalEntryId": "YTr1h2SyKlxiRIDK",
   "journalPageId": "qXgDLWSXQxbqWkTA"
  },
  {
   "slug": "glasbren",
   "name": "Glasbren",
   "out": "assets/bestiary/glasbren.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "7GtbWc7kafUVk6dI",
   "journalEntryId": "3Q3V7QXv1XFx1UK8",
   "journalPageId": "yZnBR4myriobQFz5"
  },
  {
   "slug": "hennain",
   "name": "Hennain",
   "out": "assets/bestiary/hennain.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "6RhD3Vrdb3B9GXTA",
   "journalEntryId": "3Q3V7QXv1XFx1UK8",
   "journalPageId": "yZnBR4myriobQFz5"
  },
  {
   "slug": "lithic-servant",
   "name": "Lithic Servant",
   "out": "assets/bestiary/lithic-servant.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "CoqfzAvGUkjfvMpi",
   "journalEntryId": "91EWIGU7SaOUHbS9",
   "journalPageId": "rsVBT8SKBdg0GgA3"
  },
  {
   "slug": "mosaic-swarm",
   "name": "Mosaic Swarm",
   "out": "assets/bestiary/mosaic-swarm.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "fNEJcPa37GBqXwOq",
   "journalEntryId": "qlGSzAdbwRzcPJ70",
   "journalPageId": "rRlMBzhKYM9P4fK7"
  },
  {
   "slug": "stone-sentinel",
   "name": "Stone Sentinel",
   "out": "assets/bestiary/stone-sentinel.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "mRpMqY81O24lXlPG",
   "journalEntryId": "hNTwQMEAue41DzAx",
   "journalPageId": "5hvH8z9U9TifqPZ0"
  },
  {
   "slug": "fire-vortex",
   "name": "Fire Vortex",
   "out": "assets/bestiary/fire-vortex.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "1U5ExYjZPgmW0Gck",
   "journalEntryId": "qUp7ZkpC5FdinUC4",
   "journalPageId": "MlbyZpkmaCRWrwnL"
  },
  {
   "slug": "lightning-vortex",
   "name": "Lightning Vortex",
   "out": "assets/bestiary/lightning-vortex.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "baV7yiVwXMTKa49B",
   "journalEntryId": "qUp7ZkpC5FdinUC4",
   "journalPageId": "MlbyZpkmaCRWrwnL"
  },
  {
   "slug": "water-vortex",
   "name": "Water Vortex",
   "out": "assets/bestiary/water-vortex.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "iGFc9muBkF8HMgDQ",
   "journalEntryId": "qUp7ZkpC5FdinUC4",
   "journalPageId": "MlbyZpkmaCRWrwnL"
  },
  {
   "slug": "wind-vortex",
   "name": "Wind Vortex",
   "out": "assets/bestiary/wind-vortex.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "JRoNGWPbEVDVTu1s",
   "journalEntryId": "qUp7ZkpC5FdinUC4",
   "journalPageId": "MlbyZpkmaCRWrwnL"
  },
  {
   "slug": "the-crombil",
   "name": "The Crombil, Awakened",
   "out": "assets/bestiary/the-crombil.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "i2U1Qxscwoqw6eR0",
   "journalEntryId": "EYZ5DbxfTP8Pkzmv",
   "journalPageId": "dFx9ksncRYUgW1yL"
  },
  {
   "slug": "grimstew",
   "name": "Grimstew",
   "out": "assets/bestiary/grimstew.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "qDIbc21OgAwQJvjo",
   "journalEntryId": "fSV9XtOChfthnbDG",
   "journalPageId": "13kSx63dNzKgtIQm"
  },
  {
   "slug": "aurochs",
   "name": "Aurochs",
   "out": "assets/bestiary/aurochs.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "fVOXp33igDV70sc0",
   "journalEntryId": "tx9I3QGe5ldHuhho",
   "journalPageId": "1RDme0QvQu2hp7X9"
  },
  {
   "slug": "frythanc",
   "name": "Frythanc",
   "out": "assets/bestiary/frythanc.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "YKLG7aDPRTieTkve",
   "journalEntryId": "oAW6aV8Fmw6ZQPX4",
   "journalPageId": "LJpl17rtE9oSe9Ga"
  },
  {
   "slug": "swarm-of-silvery-vermin",
   "name": "Swarm of Silvery Vermin",
   "out": "assets/bestiary/swarm-of-silvery-vermin.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "fnzABVPboAe4m9Y8",
   "journalEntryId": "5tvhzovmN18QlxGa",
   "journalPageId": "TGra87VIxIOJstZX"
  },
  {
   "slug": "yaarowslow-the-many",
   "name": "Yaarowslow, the Many",
   "out": "assets/bestiary/yaarowslow-the-many.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "xhYYoDHoyS7ZyPKz",
   "journalEntryId": "5tvhzovmN18QlxGa",
   "journalPageId": "TGra87VIxIOJstZX"
  },
  {
   "slug": "mammoth",
   "name": "Mammoth",
   "out": "assets/bestiary/mammoth.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "cy5OhsU0kVFUoppF",
   "journalEntryId": "H4EkNtJ49Mpz9O8a",
   "journalPageId": "xX3jtpeelPVMnDBu"
  },
  {
   "slug": "tcaventes",
   "name": "Tcaventes, Shackle and Key",
   "out": "assets/bestiary/tcaventes.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "GdZQKCMmPANEuFyb",
   "journalEntryId": "muAijyov4VTFfqBL",
   "journalPageId": "FNyaslzj06Ri4wHm"
  },
  {
   "slug": "soithech",
   "name": "Soithech",
   "out": "assets/bestiary/soithech.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "R3CGOnv3X1BQUpB5",
   "journalEntryId": "J0eNyUcWDLD2ornV",
   "journalPageId": "XbjOkmGBMYByEeLN"
  },
  {
   "slug": "ghostly-hounds",
   "name": "Ghostly Hounds",
   "out": "assets/bestiary/ghostly-hounds.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "3WXpoW1ajr2PCDC9",
   "journalEntryId": "6wnyTkZl7GRhVM8g",
   "journalPageId": "6Nw4LldBvZJA3Lm8"
  },
  {
   "slug": "the-pale-hunter",
   "name": "The Pale Hunter",
   "out": "assets/bestiary/the-pale-hunter.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "KEv7LnXs4zQju3lp",
   "journalEntryId": "6wnyTkZl7GRhVM8g",
   "journalPageId": "6Nw4LldBvZJA3Lm8"
  },
  {
   "slug": "skittering-horror",
   "name": "Skittering Horror",
   "out": "assets/bestiary/skittering-horror.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "mk4kCF2buJrsSlK2",
   "journalEntryId": "KcEptvDi3nhRFoBB",
   "journalPageId": "9rYFqciEnJfFIQu8"
  },
  {
   "slug": "star-mole",
   "name": "Star-Mole",
   "out": "assets/bestiary/star-mole.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "89ZjFUUS1I9bP2MH",
   "journalEntryId": "5JC9gQCHQUHugXsQ",
   "journalPageId": "nuJLbTQh1QYWWoTg"
  },
  {
   "slug": "brawzbedr",
   "name": "Brawzbedr",
   "out": "assets/bestiary/brawzbedr.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "eU2PTY1DoA2n95RT",
   "journalEntryId": "sc28aHnwvhvBDyjh",
   "journalPageId": "pAEjZrge0FusCivY"
  },
  {
   "slug": "gouzadn",
   "name": "Gouzadn",
   "out": "assets/bestiary/gouzadn.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "SerJ5gYYlRuUmI9k",
   "journalEntryId": "IS7Y75Kbqe5KILXW",
   "journalPageId": "LO7IdRIzeEGqOvjl"
  },
  {
   "slug": "grochslon",
   "name": "Grochslon",
   "out": "assets/bestiary/grochslon.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "uP9zE6MDiS3TwIWF",
   "journalEntryId": "BUMZ5O0VT9SDjfwE",
   "journalPageId": "zvAUMz9DzP5e9Aec"
  },
  {
   "slug": "corrupted-glasbren",
   "name": "Corrupted Glasbren",
   "out": "assets/bestiary/corrupted-glasbren.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "IornEAAcH3j4YRST",
   "journalEntryId": "g8AKcpFJTeVx51xV",
   "journalPageId": "9ri6PsJH7z67a7UF"
  },
  {
   "slug": "butcherbird",
   "name": "Butcherbird",
   "out": "assets/bestiary/butcherbird.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "dLxI39zRgbt5baD5",
   "journalEntryId": "vuCG2gnrr5slc2Cj",
   "journalPageId": "PSKZl8G6n6RRlEXd"
  },
  {
   "slug": "ceirwmawr",
   "name": "Ceirwmawr",
   "out": "assets/bestiary/ceirwmawr.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "Qe9HW1xQCicVwtGC",
   "journalEntryId": "idLzu8GfQknwWCby",
   "journalPageId": "nal7Fmjmg5Grpcvw"
  },
  {
   "slug": "cynddaraig",
   "name": "Cynddaraig",
   "out": "assets/bestiary/cynddaraig.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "BVvWxKNlDdOzu9Ac",
   "journalEntryId": "JWXOAXD9nd8rkB3I",
   "journalPageId": "oXF62e14JnnztVEB"
  },
  {
   "slug": "feathered-drake",
   "name": "Feathered Drake",
   "out": "assets/bestiary/feathered-drake.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "30NDurP2YczoGj6B",
   "journalEntryId": "T17yRp50eDt8cyXO",
   "journalPageId": "57hELMNqLR2FRrIf"
  },
  {
   "slug": "hagr",
   "name": "Hagr",
   "out": "assets/bestiary/hagr.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "fz8g74CpQcYrqSki",
   "journalEntryId": "ckxdN0P9cHJfsZgQ",
   "journalPageId": "dPV0t98P6gx0ClE8"
  },
  {
   "slug": "nine-fingered-stranger",
   "name": "Nine-Fingered Stranger",
   "out": "assets/bestiary/nine-fingered-stranger.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "Kh5NQGe2zSAEV3BZ",
   "journalEntryId": "SUe3zYQvT9AGKgzG",
   "journalPageId": "m9OXzvC1peHLx1TF"
  },
  {
   "slug": "plasmic-horror",
   "name": "Plasmic Horror",
   "out": "assets/bestiary/plasmic-horror.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "nh6h60KGgx2IlxfF",
   "journalEntryId": "mBQElv2JfT8AW8KH",
   "journalPageId": "jtqfx2ZFWSNH0fpi"
  },
  {
   "slug": "kyakaara",
   "name": "Kyakaara",
   "out": "assets/bestiary/kyakaara.webp",
   "actorPack": "stonetop_pwd.stonetop-bestiary",
   "actorId": "Iyc7KUONkBO5Ibyz",
   "journalEntryId": "pOtdFLTTywDCKXPM",
   "journalPageId": "aLuITGoixs7zCyQb"
  }
 ],
 "locations": [
  {
   "slug": "the-makers-roads",
   "name": "The Makers' Roads",
   "journalEntryId": "ezquwGFbne6uxzJK",
   "journalPageId": "0J5rrvhCV7xBuIej",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-makers-roads-1.webp"
    },
    {
     "out": "assets/locations/the-makers-roads-2.webp"
    }
   ]
  },
  {
   "slug": "the-stream",
   "name": "The Stream",
   "journalEntryId": "KJUzuYlurcjPxHd7",
   "journalPageId": "qg0mwTBbWwCC2bta",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-stream-1.webp"
    }
   ]
  },
  {
   "slug": "waystones",
   "name": "Waystones",
   "journalEntryId": "VrKFDEUbYMEYplMk",
   "journalPageId": "cEPBscFh8D1YRZZn",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/waystones-1.webp"
    }
   ]
  },
  {
   "slug": "blackwater-lake",
   "name": "Blackwater Lake",
   "journalEntryId": "25HD51CKompWLFvB",
   "journalPageId": "fQLW7MZEdD2lPsML",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/blackwater-lake-1.webp"
    },
    {
     "out": "assets/locations/blackwater-lake-2.webp"
    },
    {
     "out": "assets/locations/blackwater-lake-3.webp"
    },
    {
     "out": "assets/locations/blackwater-lake-4.webp"
    }
   ]
  },
  {
   "slug": "ferriers-fen",
   "name": "Ferrier's Fen",
   "journalEntryId": "UstvXnD6EA9IBBO3",
   "journalPageId": "MjRt3VmyHvOLKjkx",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/ferriers-fen-1.webp"
    },
    {
     "out": "assets/locations/ferriers-fen-2.webp"
    }
   ]
  },
  {
   "slug": "huffel-peaks",
   "name": "Huffel Peaks",
   "journalEntryId": "RxUdCkI2lL6gE5IH",
   "journalPageId": "g4LGaNLHpQnCjw6E",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/huffel-peaks-1.webp"
    },
    {
     "out": "assets/locations/huffel-peaks-2.webp"
    }
   ]
  },
  {
   "slug": "lygos-and-the-south",
   "name": "Lygos & the South",
   "journalEntryId": "DPUvs6Ss8UHXEsCJ",
   "journalPageId": "ZrWwwzUrqugxjDU8",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/lygos-and-the-south-1.webp"
    },
    {
     "out": "assets/locations/lygos-and-the-south-2.webp"
    },
    {
     "out": "assets/locations/lygos-and-the-south-3.webp"
    },
    {
     "out": "assets/locations/lygos-and-the-south-4.webp"
    },
    {
     "out": "assets/locations/lygos-and-the-south-5.webp"
    }
   ]
  },
  {
   "slug": "north-manmarch",
   "name": "North Manmarch",
   "journalEntryId": "NERZ6p7FNc1pxNWL",
   "journalPageId": "5FyaezhZEfD7MSAR",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/north-manmarch-1.webp"
    },
    {
     "out": "assets/locations/north-manmarch-2.webp"
    },
    {
     "out": "assets/locations/north-manmarch-3.webp"
    },
    {
     "out": "assets/locations/north-manmarch-4.webp"
    }
   ]
  },
  {
   "slug": "south-manmarch",
   "name": "South Manmarch",
   "journalEntryId": "apczJSWiu0M5dFrF",
   "journalPageId": "OEmiJvwbFOwASSK3",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/south-manmarch-1.webp"
    }
   ]
  },
  {
   "slug": "the-dread-river",
   "name": "The Dread River",
   "journalEntryId": "lGNIQWIn8CPHuM7E",
   "journalPageId": "rqFWDXswIplr4L8s",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-dread-river-1.webp"
    },
    {
     "out": "assets/locations/the-dread-river-2.webp"
    },
    {
     "out": "assets/locations/the-dread-river-3.webp"
    }
   ]
  },
  {
   "slug": "the-flats",
   "name": "The Flats",
   "journalEntryId": "nBvsH19B1bG2d4Di",
   "journalPageId": "hnfjCiDIWr2QPUuR",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-flats-1.webp"
    },
    {
     "out": "assets/locations/the-flats-2.webp"
    },
    {
     "out": "assets/locations/the-flats-3.webp"
    },
    {
     "out": "assets/locations/the-flats-4.webp"
    }
   ]
  },
  {
   "slug": "the-foothills",
   "name": "The Foothills",
   "journalEntryId": "61j2hjMjANZcniEQ",
   "journalPageId": "HIqfyyRDZUeRduJu",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-foothills-1.webp"
    },
    {
     "out": "assets/locations/the-foothills-2.webp"
    },
    {
     "out": "assets/locations/the-foothills-3.webp"
    }
   ]
  },
  {
   "slug": "the-frozen-wastes",
   "name": "The Frozen Wastes",
   "journalEntryId": "xg8MEuSbbEt1wqg8",
   "journalPageId": "UG08UT7YAyN8GoNa",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-frozen-wastes-1.webp"
    }
   ]
  },
  {
   "slug": "the-great-wood",
   "name": "The Great Wood",
   "journalEntryId": "6kt1b8ozEREDCi4k",
   "journalPageId": "OwbdRU0YCyF9qvEC",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-great-wood-1.webp"
    },
    {
     "out": "assets/locations/the-great-wood-2.webp"
    }
   ]
  },
  {
   "slug": "the-labyrinth",
   "name": "The Labyrinth",
   "journalEntryId": "v4slCO5mFJLcZO1q",
   "journalPageId": "0xOQrhcQ8wJFsgjT",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-labyrinth-1.webp"
    },
    {
     "out": "assets/locations/the-labyrinth-2.webp"
    },
    {
     "out": "assets/locations/the-labyrinth-3.webp"
    }
   ]
  },
  {
   "slug": "the-steplands",
   "name": "The Steplands",
   "journalEntryId": "No8UN1MJEb2mrLXo",
   "journalPageId": "L9aafiUeKDne11Hj",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-steplands-1.webp"
    },
    {
     "out": "assets/locations/the-steplands-2.webp"
    }
   ]
  },
  {
   "slug": "the-whitefang-mountains",
   "name": "The Whitefang Mountains",
   "journalEntryId": "5vFbBIn18TKtCF91",
   "journalPageId": "9ok9WOFH6pB5E4YF",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-whitefang-mountains-1.webp"
    },
    {
     "out": "assets/locations/the-whitefang-mountains-2.webp"
    }
   ]
  },
  {
   "slug": "three-coven-lake",
   "name": "Three Coven Lake",
   "journalEntryId": "zUeBMA1XS4Lq3KdK",
   "journalPageId": "Ol7oAcADxdClvGZw",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/three-coven-lake-1.webp"
    },
    {
     "out": "assets/locations/three-coven-lake-2.webp"
    }
   ]
  },
  {
   "slug": "barrier-pass",
   "name": "Barrier Pass",
   "journalEntryId": "VZ3YkXn70E1C7TEO",
   "journalPageId": "DPRYimNgfDixBLBO",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/barrier-pass-1.webp"
    },
    {
     "out": "assets/locations/barrier-pass-2.webp"
    },
    {
     "out": "assets/locations/barrier-pass-3.webp"
    }
   ]
  },
  {
   "slug": "gordins-delve",
   "name": "Gordin's Delve",
   "journalEntryId": "HesP5wBhjA0l9Ffk",
   "journalPageId": "rlqWn9hRa5shvUlY",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/gordins-delve-1.webp"
    },
    {
     "out": "assets/locations/gordins-delve-2.webp"
    },
    {
     "out": "assets/locations/gordins-delve-3.webp"
    },
    {
     "out": "assets/locations/gordins-delve-4.webp"
    },
    {
     "out": "assets/locations/gordins-delve-5.webp"
    }
   ]
  },
  {
   "slug": "marshedge",
   "name": "Marshedge",
   "journalEntryId": "uXlyry9CpXUz4ooR",
   "journalPageId": "TJgCT9BQixIEAHly",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/marshedge-1.webp"
    },
    {
     "out": "assets/locations/marshedge-2.webp"
    }
   ]
  },
  {
   "slug": "red-groves",
   "name": "Red Groves",
   "journalEntryId": "o7qpevFfrKXuVlGo",
   "journalPageId": "aAeE7ctFDrQpPARL",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/red-groves-1.webp"
    }
   ]
  },
  {
   "slug": "the-crombil",
   "name": "The Crombil",
   "journalEntryId": "UEQE5cKRurhX9gCE",
   "journalPageId": "mZBuG8teOiJRc49k",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-crombil-1.webp"
    }
   ]
  },
  {
   "slug": "the-golden-oak",
   "name": "The Golden Oak",
   "journalEntryId": "2NsZu7ZKzdrEHfjk",
   "journalPageId": "zK6zVWbEucrqHQs0",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-golden-oak-1.webp"
    }
   ]
  },
  {
   "slug": "the-maw",
   "name": "The Maw",
   "journalEntryId": "vwP9YSr3qrc4Tq7k",
   "journalPageId": "4GEczlSnuypaAiEX",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-maw-1.webp"
    }
   ]
  },
  {
   "slug": "the-ruined-tower",
   "name": "The Ruined Tower",
   "journalEntryId": "iYSktNtms4NQat8F",
   "journalPageId": "3MC797saOr3wnXwd",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-ruined-tower-1.webp"
    },
    {
     "out": "assets/locations/the-ruined-tower-2.webp"
    },
    {
     "out": "assets/locations/the-ruined-tower-3.webp"
    },
    {
     "out": "assets/locations/the-ruined-tower-4.webp"
    }
   ]
  },
  {
   "slug": "the-village-of-stonetop",
   "name": "The Village of Stonetop",
   "journalEntryId": "6yScslDfqrcCQ6CJ",
   "journalPageId": "x2BcdS6EFxG0Ic3F",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-village-of-stonetop-1.webp"
    },
    {
     "out": "assets/locations/the-village-of-stonetop-2.webp"
    },
    {
     "out": "assets/locations/the-village-of-stonetop-3.webp"
    },
    {
     "out": "assets/locations/the-village-of-stonetop-4.webp"
    },
    {
     "out": "assets/locations/the-village-of-stonetop-5.webp"
    },
    {
     "out": "assets/locations/the-village-of-stonetop-6.webp"
    }
   ]
  },
  {
   "slug": "titan-bones",
   "name": "Titan Bones",
   "journalEntryId": "fc9yqAlxCCgZVckC",
   "journalPageId": "oMNmCXgSQSkxerEK",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/titan-bones-1.webp"
    }
   ]
  },
  {
   "slug": "ustrina",
   "name": "Ustrina",
   "journalEntryId": "MZIqm0QhN3lxNKuO",
   "journalPageId": "B2W00k1wl8ClNwAz",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/ustrina-1.webp"
    }
   ]
  },
  {
   "slug": "vor-svetelik",
   "name": "Vor Svetelik",
   "journalEntryId": "76FKkdtTFxWEGIKQ",
   "journalPageId": "lWEakMs4PwHgcfiW",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/vor-svetelik-1.webp"
    },
    {
     "out": "assets/locations/vor-svetelik-2.webp"
    },
    {
     "out": "assets/locations/vor-svetelik-3.webp"
    },
    {
     "out": "assets/locations/vor-svetelik-4.webp"
    }
   ]
  },
  {
   "slug": "the-things-below",
   "name": "The Things Below",
   "journalEntryId": "5Kym1qDHTmM8XUQ6",
   "journalPageId": "roHUFm71o2upL6Yt",
   "sectionIndex": 0,
   "images": [
    {
     "out": "assets/locations/the-things-below.webp"
    }
   ]
  }
 ]
};
